### ISSUE TITLE
lsp-ui

### ISSUE THREAD

**Issue by andreyorst** [kak-lsp/kak-lsp#107]
Since Kakoune has info boxes that can be shown at given coordinates, they can be used to display useful info much like [Emacs lsp-ui package](https://github.com/emacs-lsp/lsp-ui) does.

**Comment by ul** [comment]
I like this idea, now we need to design what, where and when to show. Not sure that it's on the top of priorities for my own use-case of kak-lsp, but if this issue would get traction I'm more than keen to participate both in design and implementation stages.

**Comment by andreyorst** [comment]
In emacs, lsp-ui shows documentations to the symbols at which cursor is positioned.
![image](https://user-images.githubusercontent.com/19470159/46954576-a3b63080-d099-11e8-8d30-912dd48f1245.png)
I think it is bit annoing to se it all the time, however it's quite handy when you explore some new, well documented codebase. I see this feature as a general `info` box, that has function name as a `-title` and documentation as main body.
![image](https://user-images.githubusercontent.com/19470159/46954933-6b632200-d09a-11e8-9c78-f96a3650079e.png)

It also add overlay with variable state information like values and other information
![image](https://user-images.githubusercontent.com/19470159/46954990-8df53b00-d09a-11e8-8464-cf2dd009d440.png)
which can be added by using `-ancor` swithc with `title` command:

![image](https://user-images.githubusercontent.com/19470159/46955207-0fe56400-d09b-11e8-92db-46e42633bc58.png)
Although it doesn't occupy space if text is there, and is being displayed lower, and at the right side of the screen. Position can be calculated though.

**Comment by ul** [comment]
I wonder if `lsp-auto-hover-enable` + `set global lsp_hover_anchor true` covers this use-case?

**Comment by andreyorst** [comment]
Oh. Yes, this looks like it covers the use-case for hovering, but I'd like to set some sort of timeout for it. I'm not sure if this is possible though.

Documentation better should go to separated info box, since it will not cover code if it is too big.

**Comment by andreyorst** [comment]
> set global lsp_hover_anchor false will keep info box in the default place. Actually, we can add third placement option like on lsp-ui screenshots, on the same line as cursor, but at the right border.

I'm mostly saying about showing documentation is the default place while keeping hover behavior too. I know that multiple selections are not supported, but I don't need documentation most of the time, so I would like to have hover near the cursor, and when I explicitly want to see doc, I just execute `lsp-doc` which is shown in the default place.

**Comment by andreyorst** [comment]
> I'm aware only about LSP textDocument/hover method (which is used by kak-lsp) and can't find any method for requesting documentation separately.

I'm afraid there's no such method. I don't know how it is done in Emacs package, but what it does essentially is that it distinguish documentation from other hover information about the scope. You can see that documentation is shown separately in the other place on the screen, and hover info is shown at the right side of the screen:
![image](https://user-images.githubusercontent.com/19470159/47407924-eba61900-d765-11e8-812a-084932e25bfb.png)
In this package user may move documentation from graphical box to the text box area at the bottom of the Emacs window, or disable it completely (IIRC), so only hover info will be shown. It is nice to have, since Documentation can be pretty big and cover lot of screen space, and also it can be pretty useless.

I know that in current state Kakoune cannot show more than one info box: https://github.com/mawww/kakoune/issues/1516, and has general problems with displaying huge messages in it, so it will be great to have a method that can get all hover info from the server, distinguish documentation from hover info, and print those two as separate info boxes, one of which could be triggered manually.

**Comment by ul** [comment]
I need to check it, but I suspect that lsp-ui treats first element of hover response as an actual hover info and the rest as a documentation. It feels a bit fragile (I guess some language servers follow this convention and some not), but if we will provide user a choice (e.g. `lsp_split_hover` option) it might be acceptable solution.

**Comment by losnappas** [comment]
Could I somehow put the signature help into the balloon instead of the statusline?

Also, I quite like this feature from PHPStorm.

![phpstorm](https://user-images.githubusercontent.com/25119292/56079824-0be79400-5de9-11e9-9567-30d5983c171d.png)

On the left side you see the argument names as virtual text, and they stay there forever. Makes quickly overviewing code much easier.

**Comment by andreyorst** [comment]
> Also, I quite like this feature from PHPStorm.

Related issue on Kakoune side: https://github.com/mawww/kakoune/issues/2536
