### ISSUE TITLE
Support multiple language servers per filetype

### ISSUE THREAD

**Issue by ul** [kak-lsp/kak-lsp#17]
Use case: for javascript files I want diagnostics from both eslint and flow language servers.

**Comment by EmmChriss** [comment]
Contextual language recognition would be practically impossible, but a comment-based approach could be feasible

**Comment by gbrlsnchs** [comment]
This would enable using [`diagnostic-languageserver`](https://github.com/iamcco/diagnostic-languageserver) to lint code and also run formatters not supported by LSP servers themselves.

**Comment by perpen** [comment]
Or could we make a "proxy" language server, which kak-lsp talks to, and that interacts with potentially multiple language servers?

**Comment by ul** [comment]
The proxy solution has benefits that it potentially could be re-used outside of kak-lsp. We need to draft how is it supposed to behave, i.e. merge strategies for various responses etc.

**Comment by joefiorini** [comment]
I know this issue is a little stale, but I just found [a project that proxies to multiple language servers](https://github.com/wylieconlon/jsonrpc-ws-proxy). Has anyone tried this?

**Comment by krobelus** [comment]
> I know this issue is a little stale

I think it's still a good idea, especially considering that VSCode already supports that (it can display diagnostics from multiple language servers, for example).

> I don't see anything about this that would enable running different language servers against a single file simultaneously.

Right, it looks like this project only forwards requests to one language server.

We need something that forwards one request to (potentially) multiple servers. I like to call it `language-server-tee` like the `tee` command.
It only needs to support stdio mode for kak-lsp, not TCP.

Merging strategies can get a bit complicated, but if we start by showing the union of all diagnostics (and take everything else only from a "primary" language server) that sounds easy and could already be good enough?

**Comment by gbrlsnchs** [comment]
> We need something that forwards one request to (potentially) multiple servers.

Wouldn't that imply having to provide the same set of configurations from an individual language server to this "sink" language server as well? This feels a little redundant.

Also, this strategy would leave the responsibility of managing processes up to the sink server, which is not always desired.

I think this would only be useful for `kak-lsp` while it doesn't support multiple servers, but I don't see value for other projects. Other editors like Neovim and Emacs already support multiple language servers at a client level, which IMO is a sane long-term decision.

If we consider a client-level approach, what are the current blockers that make supporting multiple language servers unviable in `kak-lsp`?

**Comment by krobelus** [comment]
On Mon, Nov 14, 2022 at 11:25:23AM -0800, Gabriel Sanches wrote:
> If we consider a client-level approach, what are the current blockers that make supporting multiple language servers unviable in `kak-lsp`?

none that I know of

**Comment by raiguard** [comment]
Adding my usecase: I run `lua-language-server` for my Factorio modding projects. A fellow modder recently released a small language server for Factorio's locale system, which includes autocomplete of localised strings in Lua code. I currently can't run both servers at once in Lua files.

**Comment by krobelus** [comment]
looks like someone implemented the proxy language server, see https://github.com/messense/multi-lsp-proxy
haven't tried it yet

**Comment by gbrlsnchs** [comment]
Anyone here willing to try https://github.com/kak-lsp/kak-lsp/pull/686? It shouldn't be too hard to set up a multi-language config.
