### ISSUE TITLE
Implement window/showMessageRequest

### ISSUE THREAD

**Issue by benjumanji** [kak-lsp/kak-lsp#183]
This would be rally helpful for scala support as scala metals uses this to trigger automatic build imports. I think it could work as follows:

kak-lsp buffers requests. Users add a hook for idling events. On idle poll for server requests. If there is are pending requests dequeue one display via infobox with keymaps to select option to send back.

If we had an implementation path I'd be willing to work on this.

**Comment by benjumanji** [comment]
Actually thinking a bit harder we can obviously do better. When we get a message we can set an option kak to let it know there is something waiting. On idle hook then configures bindings for a user mode and enters it. Bindings deal with sending the options back. That seems like it would be pretty slick.

**Comment by ul** [comment]
> On idle hook then configures bindings for a user mode and enters it.

This is pretty neat! And message option could be a list by itself, so kak-lsp server wouldn't need to buffer requests at all.

Implementing the response part might require some improvements in kak-lsp architecture, please let me know if I can help with it.

**Comment by benjumanji** [comment]
I forgot options could be lists. That's neat. I'll make a straw man of the interface this weekend and probably try hacking in the lsp part the weekend after.

**Comment by benjumanji** [comment]
I'm currently stuck on the user interface, but I haven't given up yet.

https://discuss.kakoune.com/t/faking-enter-user-mode-dismiss-info-box/416

**Comment by topisani** [comment]
@benjumanji if you continued being stuck at that point, I think you can use `on-key` to solve it.

**Comment by Gskartwii** [comment]
Hi! How about using Kakoune's `prompt` or `menu` commands for this? (See `:doc commands`)

The feature would be quite important to me, precisely to use scala-metals. I could try making a PR if I can get some pointers on how it should work.

**Comment by benjumanji** [comment]
hi hi, I've unfortunately completely run out of time / motivation to work on this, so if anyone else wants to take up the mantle they should feel free.

**Comment by benjumanji** [comment]
I tried using prompt in the past and found it hard to get the right behaviour with on key to make it work, but I'm sure someone else could probably figure something out :)

**Comment by Gskartwii** [comment]
> I tried using prompt in the past and found it hard to get the right behaviour with on key to make it work, but I'm sure someone else could probably figure something out :)

Finicky stuff. I'm curious why it should use on-key instead of the default prompt behaviour (displaying options selectable with arrow keys).

**Comment by igor-ramazanov** [comment]
I think this can be closed, as it was done in https://github.com/kak-lsp/kak-lsp/pull/679
