### ISSUE TITLE
Weird hover position

### ISSUE THREAD

**Issue by andreyorst** [kak-lsp/kak-lsp#203]
Happens in normal mode to me in Rust filetype:

![image](https://user-images.githubusercontent.com/19470159/57749385-8b1d0000-76e6-11e9-86d6-43a789ae089c.png)

Kakoune is `v2019.01.20-255-g49164710`, your plugin is current master: 402368fbe10881af32c89fe0524d35a4e596f5ef

**Comment by krobelus** [comment]
Can you still reproduce?

**Comment by andreyorst** [comment]
Sorry, I no longer use kakoune to edit code, and I don't use kak-lsp, so I
don't know. Feel free to close it if it's not reproducible on your side

**Comment by krobelus** [comment]
Thanks - I should get back into emacs at some point, their lsp-mode looks fantastic ;)
