### ISSUE TITLE
Does this implement workspace/configuration?

### ISSUE THREAD

**Issue by razzeee** [kak-lsp/kak-lsp#234]
Hey there, a user brought this to my attention, but I'm not 100% sure.
Are you implementing `workspace/configuration`? https://microsoft.github.io/language-server-protocol/specification#workspace_configuration

We got that idea due to this issue.
https://github.com/elm-tooling/elm-language-server/issues/154

**Comment by ul** [comment]
Hey @Razzeee, no, this request is not implemented atm.

**Comment by Razzeee** [comment]
So that would explain why my refactoring to the now api broke with kak-lsp.

**Comment by Razzeee** [comment]
I'm falling back to the old way to do this, when the client communicates that it does not implement this endpoint. So it's fine for the moment.

**Comment by reykjalin** [comment]
Are there any plans to implement support for `workspace/configuration` at the moment? I just hit an issue with Intelephense that can't be resolved without support for `workspace/configure` see bmewburn/vscode-intelephense#1443.

I'd be happy to try to put something together over the next couple of weeks, but would need some guidance on where to begin adding an implementation. If that would be of any assistance of course 🙂.

**Comment by krobelus** [comment]
@reykjalin support for `workspace/configuration` was recenetly merged to master.
However, on master we simply re-use `initialization_options`, which are incompatible. That causes problems on gopls.
I've just opened #507, which adds a dedicated option for that `workspace/configuration`, see the documentation. Please try if it works for you if you will.
