### ISSUE TITLE
Multiple kak-lsp processs start since v6.2.0

### ISSUE THREAD

**Issue by vnagarnaik** [kak-lsp/kak-lsp#253]
Since v6.2.0 I had trouble getting proper completions and hover info. I didn't debug it as I was busy with some projects. I had to turn off kak-lsp. Now I retried with v7.0.0 and still see this issue so filing the bug now.

I see that when initializing kak-lsp, somehow there are multiple kak-lsp processes started. Each process has its own child language server process. And most of the lsp commands don't work at that point. When I tried going back to older releases, I can reliably reproduce this issue in v.6.2.0 and later. v6.1.0 does not show this issue. However, due to compatibility issues with newer Kakoune version, I don't get completions. But hover info and other commands run successfully.

When debugging I tried to turn on logging but I don't see any obvious errors there. I also don't see anything logged in `*debug*` buffer.

Let me know how I can help with further debugging. Or may be I am missing some initialization steps.

This is my kak-lsp start snippet:

```
define-command start-kak-lsp -docstring 'Start kak-lsp for this session' %{
    #──────────────
    # Start kak-lsp
    #──────────────
    evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
    # Remove following lines after debugging phase is over.
    # For kak-lsp 7.0.0
    # set-option global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"
    # For kak-lsp 6.2.1 and earlier
    nop %sh{ bash -c 'kak-lsp -s $kak_session -vvv > /tmp/kak-lsp.log 2>&1 < /dev/null &' }
    # Enable kak-lsp.
    # lsp-enable
    # Override file completions when starting kak-lsp.
    set-option global completers filename 'option=lsp_completions'
    # Configure kak-lsp behavior.
    lsp-auto-hover-enable
    lsp-diagnostic-lines-disable global
    # After writing a buffer, get updated diagnostics.
    hook -group vbn-ide global BufWritePost .* %{ evaluate-commands -no-hooks lsp-diagnostics }
    # Always show signature help. But with separate info box.
    define-command -override lsp-show-signature-help -params 2 -docstring %{
        Render signature help
    } %{
        info -anchor %arg{1} %arg{2}
    }
    lsp-auto-signature-help-enable
}
```

**Comment by ul** [comment]
Do you have a config file in place? kak-lsp should work without it but there is at least one report that explicitly copying default config file solves a problem similar to yours: https://github.com/ul/kak-lsp/issues/271#issuecomment-569416825

If it’s the case it would be cool to investigate it as I fail to reproduce it locally and wonder what exactly happens there.

**Comment by krobelus** [comment]
probably stale, please reopen if this still happens
