### ISSUE TITLE
Dealing with `lsp-auto-hover-enable` and large info boxes

### ISSUE THREAD

**Issue by maximbaz** [kak-lsp/kak-lsp#257]
I use `lsp-auto-hover-enable` and it's generally good, except when I stumble upon info boxes that contain a lot of information.

In such cases it's possible that the info box will cover almost 100% of my editor, so I no longer see the context (the code where my cursor is).

Here's me navigating in a Go project, I'm pressing `h` to move left, and once I hit the big info box I try to cancel it with `Esc`:

![info](https://user-images.githubusercontent.com/1177900/69231686-d1698500-0b89-11ea-8aed-bf584bd62577.gif)

I would like to brainstorm how this UX can be improved 🙂 

One obvious idea would be to support `Esc`, so that if I press it, the info box should not reappear instantly, until I move cursor.

Another idea would be perhaps to limit the amount of text that can be displayed in the info box, cut it and add ellipsis in the end.

Maybe we could detect the cursor position and make sure the info box will never overlap with the cursor?

**Comment by maximbaz** [comment]
Right after I posted the message I learned about 
`lsp_hover_anchor` and `lsp_hover_max_lines` parameters...

These two help already, but I would like `kak-lsp` do that for me if possible, in other words in the situation like on the picture below (with both options enabled), I would like `kak-lsp` to limit the hover information to as many lines as possible that will not overlap with my cursor:

![image](https://user-images.githubusercontent.com/1177900/69232411-4db09800-0b8b-11ea-81ee-f2b942cc79d9.png)

**Comment by JJK96** [comment]
Maybe this should be fixed on the kakoune side by handling info boxes that are too big by for example rendering only a portion of it, or making it scrollable.

**Comment by clad26** [comment]
Any fix for this？

**Comment by clad26** [comment]
@mawww I think a scrollable infobox would fix the above issue...
The only problem being, is it possible or not
If it isn't, I can start toying with kak-lsp to see if I can achieve a better hovering...

**Comment by tylercecil** [comment]
I think mawww/kakoune#4043 would be needed to do this (which seems like a good idea to me). I have no idea how hard that would be...

In the meantime, I think @maximbaz is right — `Esc` should  properly deal  with `lsp-auto-hover-enable`.

Is there any way to direct `lsp-hover` output to something other than an info box? Like to another buffer?
