### ISSUE TITLE
Content of hover missing escape backslashes depending on context.

### ISSUE THREAD

**Issue by vbauerster** [kak-lsp/kak-lsp#261]
I've noticed that content of hover info box differs depending on how it was triggered.

For example following was triggered while typing in insert mode.
Note the line `let mut iter = " Mary...`, it's missing escape backslashes.
[![Screenshot-2019-11-22-at-12-40-45.png](https://i.postimg.cc/mrNf6PpH/Screenshot-2019-11-22-at-12-40-45.png)](https://postimg.cc/WD3Hd1vN)

And here hover triggered in normal mode with `lsp-hover` command.
Note the line `let mut iter = " Mary...`. Now it includes escape backslashes.
[![Screenshot-2019-11-22-at-12-49-13.png](https://i.postimg.cc/pr1tY3Gc/Screenshot-2019-11-22-at-12-49-13.png)](https://postimg.cc/H85KTvCb)

My question is it on purpose? Can we preserve escape backslashes in hover boxes in any cases?

**Comment by ul** [comment]
No, it's not intended, thanks for reporting!

**Comment by krobelus** [comment]
This is fixed in the latest release, probably by #513
