### ISSUE TITLE
Race condition between didSave and completion

### ISSUE THREAD

**Issue by danr** [kak-lsp/kak-lsp#267]
I kept getting the wrong typescript completions when writing `object.`, I got the completions for `object ` instead. I realized what the problem is: `lsp-completion` directly runs `lsp-did-change`: 
https://github.com/ul/kak-lsp/blob/243da6cb8ffa4e5367f5777d2fc48a1a9c30b875/rc/lsp.kak#L103
However, `lsp-did-change` asynchronously sends the buffer contents to the `kak-lsp` binary.  So there is as race between that and the message `lsp-completion` sends to the binary. And indeed didChange loses, presumably because it spawns other binaries such as `sed` and the script for completions is much simpler.

One way to solve this would be to make a command `lsp-did-change-and-then` taking an extra argument to run that will be guaranteed to run after the new buffer contents has been sent.

**Comment by ul** [comment]
Good catch! I followed your suggestion, please let me know if hit any problems with the implementation.

**Comment by danr** [comment]
Hi ul,

There is still a race condition. We now have that `lsp-completion` calls `lsp-did-change-and-then lsp-completion-request`. But when the new buffer content has been sent and `lsp-completion-request` is run it is now evaluated in the current editor state so it can refer to new characters. What is needed is that the kak variables are evaluated at the same time as `lsp-did-change-and-then`. This is annoying to do because of kakoune escaping.

I would move the didChange logic into the rust code. Kakoune would then send a completion request and the rust world would figure out if it first needs to send didChange and then synchronously wait for acknowledgement from the language server and then send the completion request.
