### ISSUE TITLE
lsp-formatting-sync sometimes hangs indefinitely

### ISSUE THREAD

**Issue by sclu1034** [kak-lsp/kak-lsp#273]
While working on a Rust project, `:w` commands frequently stop at `Waiting for shell command to finish (...s)`. I've been able to track it down to `lsp-formatting-sync`, specifically [the line `cat ${pipe}`](https://github.com/ul/kak-lsp/blob/996e483bb86c6116988e533790235cb4e4105b51/rc/lsp.kak#L523).

My current `kak-lsp`-related config looks like this:

```kakrc
plug "ul/kak-lsp" do %{
	cargo build --release --locked
	cargo install --force --path .
} config %{
	set-option global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

	hook -group lsp global KakEnd .* lsp-exit

	hook global WinSetOption filetype=(c|cpp|javascript|go|typescript|ruby|rust) %{
		set-option window lsp_auto_highlight_references true
		set-option window lsp_hover_anchor false
		lsp-auto-hover-enable
		lsp-enable-window
	}

	hook global WinSetOption filetype=rust %{
		hook window BufWritePre .* lsp-formatting-sync
	}
}
```

I'm not able to build a reliable test case to reproduce this issue, but I did get it to happen twice in short succession while writing a short test file.

I wrote this bit, then saved for the first time, which worked fine:

```rust
use std::fs::File;
use std::io;

fn main() -> io::Result<()> {
    let mut file = File::open("foo.txt")?;
    let mut contents = String::new();
    file.read_to_string(&mut contents)?;
    println!("Hello, world!");
}
```

Then I added `Ok(())` at the end of `main()`, tried to save again, but got `Waiting for shell command ...`. After canceling the shell command with `Ctrl-C`, a subsequent save worked fine.
At this point I could reproduce the issue reliably:

1. Undo the `Ok(())` line with `u`.
2. Save -> does not hang.
3. Redo the `Ok(())` line with `Shift-u`.
4. Save -> `Waiting for shell command ...`.

Then I typed `use std::io::prelude::*;` at the top of the file and got the same situation. I got `Waiting for shell command ...` on the initial save after adding the line as well as on any save after "toggling" the line with the steps described above.

Here are the log files for the above scenarios (without any undo-redo stuff though). The line of `=`s indicates where the editor was "waiting". https://gist.github.com/SirAiedail/59383bd24556521bba957987698bdac3

The interesting bit is that even when it hangs on a save, if I cancel the shell command and immediately save the same buffer content again, it usually works fine and successfully formats the buffer.

In a bigger project I usually only get this issue every once in a while. And while I haven't figured out a reliable way to trigger it there, it seems to me that it is more likely to happen if the buffer contains some kind of error.
However, just having an error in the buffer does not guarantee for this to happen. And syntax errors sometimes trigger the expected "Formatting could not finish" message instead of `Waiting for shell command ...`.

**Versions:**
```sh
$ uname -a
Linux vesuv 5.4.3-1-MANJARO #1 SMP PREEMPT Fri Dec 13 08:54:04 UTC 2019 x86_64 GNU/Linux

$ kak -version
Kakoune v2019.12.10-41-g62b4780e

$ kak-lsp
kak-lsp 7.0.0-snapshot
```
(kak-lsp built from master a couple days ago)

**Comment by ul** [comment]
Thanks for a detailed report!

Let me start with a minor note that you might want to move `lsp-auto-hover-enable` out of `WinSetOption` hook as it creates a global hook each time it's called and you can end up with a storm of hover requests on each move.

Judging by the log you posted, I think this is what happens: RLS dies and kak-lsp starts cleaning up after it so the next request will spin up a new instance. But the next request arrives in the middle of cleanup, kak-lsp fails to detect that and adds request to the queue but the response never arrives and FIFO stays open.

We definitely need to make sure that the controller is removed as soon as the connection to the language server is lost.

Also, I wonder if the reason for RLS crash is a malformed request from kak-lsp or is it just a bug in RLS itself:
```
Dec 31 10:57:56.921 DEBG From server: {"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}, module: kak_lsp::language_server_transport:149
Dec 31 10:57:56.932 ERRO Language server error: [2019-12-31T09:57:56Z ERROR rls::server] Can't read message
, module: kak_lsp::language_server_transport:52
```

**Comment by ul** [comment]
I think I managed to hit it locally and my new theory is:

1. RLS analyses file.
2. User changes buffer, the new version is sent to kak-lsp and then to RLS.
3. RLS publishes diagnostics for the previous version of the buffer.
4. kak-lsp tries to translate diagnostic positions to Kakoune coordinates using the new version and explodes. It's (almost) fine, it will exit soon and the next request will spin up a new kak-lsp session.
5. But during that time save request is sent. The current session is still able to receive it but unable to process. FIFO stays open as the result and Kakoune hangs.

**Comment by ul** [comment]
I *think* I improved it a little bit. It's still possible to hang it up but subjectively I need to undo/redo more ferociously for that =)

I'll continue looking for a more robust solution. Please let me know if the latest master makes the problem less annoying or not.

**Comment by SirAiedail** [comment]
Thank you for the response.

I won't be able to get to testing the next few days. But once I've got some time, I'll try both moving `lsp-auto-hover-enable` and the new master.
