### ISSUE TITLE
lsp-definition and lsp-hover not working consistently for python

### ISSUE THREAD

**Issue by Invarianz** [kak-lsp/kak-lsp#283]
`kakoune` is version `2020.01.16`, `kak-lsp` is version `7.0.0` and `pyls` is version `0.31.7`

I was testing the usage of kak-lsp with the python-language-server and found the command `lsp-definition` and `lsp-hover` to not work on every function. I cannot find out what is the underlying issue here.

First the problem with `lsp-hover`, for some functions it works, for others there is no output at all:
![hover-problem](https://user-images.githubusercontent.com/24905747/73549469-8f3aaa80-443a-11ea-92b6-7f464d484907.gif)

A similar issue is related to `lsp-definition`, where for some functions the buffer with the proper definition is openend. For others nothing happens:
![goto-problem](https://user-images.githubusercontent.com/24905747/73549584-c3ae6680-443a-11ea-90e5-40d78a0a67e3.gif)

**Comment by caksoylar** [comment]
FWIW I get the same behavior with [vim-lsp](https://github.com/prabirshrestha/vim-lsp) with the same pyls version.

**Comment by eko234** [comment]
I'm using lua-lsp and something similar happens to me, but when i retry hover or goto def, it eventually works, can You confirm ir the same happens?, Pressing esc and trying again kinda works.

**Comment by krobelus** [comment]
I can no longer reproduce
