### ISSUE TITLE
Configuration location under Mac OS is surprising

### ISSUE THREAD

**Issue by Phlogistique** [kak-lsp/kak-lsp#293]
Hi,

The configuration location under Mac OS X is `/Users/.../Library/Preferences/kak-lsp`, as returned by `dirs::config_dir` https://docs.rs/dirs/2.0.2/dirs/fn.config_dir.html whereas Kakoune uses `/Users/.../.config/kak`.

Technically, `kak-lsp` is following the OS's convention and Kakoune is violating it, but that's still surprising as a user.

As Kakoune will probably not stop supporting `~/.config`, I think `kak-lsp` should hardcode support with `.config/kak-lsp` in order to be less surprising to Kakoune users.

Would you be open to accepting such a patch? Otherwise a warning in the README would be appropriate.

**Comment by theowenyoung** [comment]
this is really painful for me, readme.md just give the wrong doc about the path in macOS. I figured this out by running the source code...

**Comment by krobelus** [comment]
Yes, we should use `~/.config/kak-lsp` even on macOS (we can still use the current location as fallback).
Will be a nice to simplify the README a bit.
