### ISSUE TITLE
kak-lsp break 'last entered command' register

### ISSUE THREAD

**Issue by joeitu** [kak-lsp/kak-lsp#298]
## step to reproduce
install kak-lsp has explain in the README
open a file with kak and enter:
`:echo yes<ret>`
then try:
`i<c-r>:` or `":p` 
## expected
should write `:echo yes` to the buffer
## actual behavior
doesn't write anything, doesn't show error message.

**Comment by sucrecacao** [comment]
This has nothing to do with kak-lsp, I also have this bug and to solve it I  create multple cursor and run `i<c-r>:` on each of them.
Usually the content of the last entered command should appear on the 2 or 3rd cursor

**Comment by krobelus** [comment]
> Usually the content of the last entered command should appear on the 2 or 3rd cursor

The nth cursor has the nth command, so if you have entered 10 commands you need 10 cursors to get the last command.

You can do this dance to get the last value in a register:

```kak
define-command echo-last -params 1.. %{
	evaluate-commands -verbatim echo %sh{
		for last; do :; done
		printf %s "$last"
	}
}
echo-last %reg{colon}
```

One way to make this more intuitive is https://github.com/mawww/kakoune/pull/3105

**Comment by joeitu** [comment]
Is it possible for a command or a plugin to insert stuff in the `:` register? 

Maybe that why I have the feeling that I can't past my last entered command ( Because it is the last, since a plugin has enter a command )

**Comment by krobelus** [comment]
> Is it possible for a command or a plugin to insert stuff in the : register?

No, it's a read-only register.

What you can do is to prefix your commands with a space, so they won't be added to the history:

```
: echo-last
```

I do that for almost all mappings, so they don't interfere with my actual `%reg{:}`.

**Comment by Screwtapello** [comment]
You can totally insert stuff in the `:` register:

    :reg colon foo bar baz

...now the last three items in the history are "foo", "bar", and "baz". My [kakoune-state-save](https://gitlab.com/Screwtapello/kakoune-state-save) plugin has a `state-save-reg-load` command that does exactly this.

You may also want to try `":<a-p>` to paste *every* item in the command history, automatically adding a new selection for each one (instead of having to guess how many selections you have).
