### ISSUE TITLE
What is the correct way of selecting the next placeholder

### ISSUE THREAD

**Issue by arrufat** [kak-lsp/kak-lsp#299]
I am using kak-lsp with clangd, and whenever I autocomplete a function, the first parameter is automatically selected and I can start typing to replace it, however, I had to add a mapping to select the next placeholder:
```
map window insert -docstring 'select next placeholder' <a-n> '<esc>: lsp-snippets-select-next-placeholders<ret>'
```
The problem is that it does not behave as the first selection, here I need to press 'c' to change the selection. In the first selection I can see that I am in "enter key" mode. Is there a way to do that for the rest of the placeholders?

**Comment by ul** [comment]
I haven't used snippets much, let me summon @topisani (the author of snippet support in kak-lsp) to share this wisdom.

**Comment by topisani** [comment]
Yes, this is implemented kinda weirdly. The `enter key` mode is kind of a hack, to show the selection, but replace it as soon as a character is received. What's the opinion on it? Is it useful, should it just go to normal mode on placeholder selection, or should it delete the placeholder and go to insert mode?

**Comment by arrufat** [comment]
For me the enter key mode for the first placeholder is good, what I don't know is how to get the same behavior for the next placeholder, I'm fine with mapping the command:
lsp-snippets-select-next-placeholders

But it doesn't leave me in enter key mode, which I think is the best mode for this.

**Comment by pickfire** [comment]
I don't think using enter key to get to the next placeholder is a nice idea since some may want to really insert a newline, maybe we should have some keys in insert mode to recognize that?

**Comment by arrufat** [comment]
@pickfire sorry for the misunderstanding, I am not talking about using the enter key, but the "enter key" mode in kakoune, where a selection automatically replaced as one starts typing, without the need to press `c`. But I don't know how to trigger this mode...

**Comment by topisani** [comment]
I changed and documented the way this is done in a recent commit bdfcc5355368230031786fc7d01fa9b6f8ef834c

**Comment by arrufat** [comment]
Great, thank you. I think we can close the issue now.

**Comment by basbebe** [comment]
this
```
def -hidden insert-c-n %{
 try %{
   lsp-snippets-select-next-placeholders
   exec '<a-;>d'
 } catch %{
   exec -with-hooks '<c-n>'
 }
}
map global insert <c-n> "<a-;>: insert-c-n<ret>"
```

doesn't seem to work for me as intended.

Now, when I have the popup with all the different suggestions (some of them snippets, most not), it always just selects the first thing and I cant iterate over the list as I would be without these lines.
