### ISSUE TITLE
Help needed for cmake lsp

### ISSUE THREAD

**Issue by CharlesGueunet** [kak-lsp/kak-lsp#311]
Hello,

Thanks for this really great plugin. I try to use the [cmake-language-server](https://pypi.org/project/cmake-language-server/) inside kakoune (it has a [coc extension](https://github.com/voldikss/coc-cmake) for vim).

My setup is the following:

**kak-lsp.toml:**
```toml
[language.cmake]
filetypes = ["cmake"]
command = "cmake-language-server"
roots = [ "build/" ]
```

**kakrc:**
```
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    define-command lsp-restart %{ lsp-stop; lsp-start }
    set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"
    set-option global lsp_diagnostic_line_error_sign "!"
    set-option global lsp_diagnostic_line_warning_sign "?"
    hook global WinSetOption filetype=(cmake) %{
        map window user 'l' ': enter-user-mode lsp<ret>' -docstring 'LSP mode'
        lsp-enable-window
    }
    hook global KakEnd .* lsp-exit
}
```

When I open a CMakeLists.txt, the langage server protocol start, but as soon as I type, I receive the error:
```
cmake language server error: 'AttributeError: ''Object'' object has no attribute ''context'''
```
And no completion comes from the lsp.
I have no idea on how to investigate this, can you give me some clues on how to approch this ?

Thanks,
Charles

**Comment by ul** [comment]
After a quick look, my guess is that cmake-language-server expects `context` to present in `textDocument/completion` request. However, the spec defines it as optional (and kak-lsp doesn't provide it):
```
Request:

method: ‘textDocument/completion’

params: CompletionParams defined as follows:

export interface CompletionParams extends TextDocumentPositionParams, WorkDoneProgressParams, PartialResultParams {
	/**
	 * The completion context. This is only available if the client specifies
	 * to send this using `ClientCapabilities.textDocument.completion.contextSupport === true`
	 */
	context?: CompletionContext;
}
```
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion

I'd suggest raising an issue for cmake-language-server to properly handle the absence of the context.

**Comment by krobelus** [comment]
Seems to be fixed in cmake-language-server, please reopen if not.
