### ISSUE TITLE
Add `LineFlagWarnings` face for warning flags

### ISSUE THREAD

**Issue by evanrelf** [kak-lsp/kak-lsp#317]
Currently `kak-lsp` lets you customize the character used to represent warnings  and errors with the `lsp_diagnostic_line_warning_sign` and `lsp_diagnostic_line_error_sign` options, respectively.

Unfortunately, both these line flags use the same face, `LineFlagErrors`, meaning you have to choose one color for both types.

It would be nice if a `LineFlagWarnings` face was added so that warnings could be colored differently.

**Comment by ul** [comment]
Yes, that sounds good! PR is welcome =)

**Comment by topisani** [comment]
you can also just set `lsp_diagnostic_line_warning_sign` to `{LineFlagWarnings}!`, but wrapping it in that by default seems like a good idea

**Comment by raiguard** [comment]
This was added in #516.
