### ISSUE TITLE
duplicate id: 'cquery_semhl'

### ISSUE THREAD

**Issue by 4lptraum2enari0** [kak-lsp/kak-lsp#325]
i'm pretty new to kakoune etc.
since 2 days i'm trying to setup kak-lsp with ccls
but kakoune keeps saying:
"1:1: 'lsp-enable-window' 4:5: 'add-highlighter' duplicate id: 'cquery_semhl'

**Comment by 414owen** [comment]
This probably means you're running `lsp-enable`(`-window`) twice.

If that doesn't sound right, can you post your `kakrc` please?

**Comment by krobelus** [comment]
We print an explicit error now when `lsp-enable` is called when already enabled.
