### ISSUE TITLE
Go to definition and other functionality doesn't work in Rust files

### ISSUE THREAD

**Issue by loewenheim** [kak-lsp/kak-lsp#341]
Here is the relevant part of my `.kakrc`:
```kak
plug "ul/kak-lsp" do %{
    cargo build --release --locked
    cargo install --force --path .
} config %{
    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'

    define-command ne -docstring 'go to next error/warning from lsp' %{ lsp-find-error --include-warnings }
    define-command pe -docstring 'go to previous error/warning from lsp' %{ lsp-find-error --previous --include-warnings }
    define-command ee -docstring 'go to current error/warning from lsp' %{ lsp-find-error --include-warnings; lsp-find-error --previous --include-warnings }

    define-command lsp-restart -docstring 'restart lsp server' %{ lsp-stop; lsp-start }
    hook global WinSetOption filetype=(c|cpp|cc|rust|javascript|typescript) %{
        map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
        set-option window lsp_auto_highlight_references true
        set-option window lsp_hover_anchor false
        lsp-auto-hover-enable
        echo -debug "Enabling LSP for filtetype %opt{filetype}"
        lsp-enable-window
    }

    hook global WinSetOption filetype=(rust) %{
        set window lsp_server_configuration rust.clippy_preference="on"

        hook window BufWritePre .* lsp-formatting-sync

        hook window -group rust-inlay-hints BufReload .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints NormalIdle .* rust-analyzer-inlay-hints
        hook window -group rust-inlay-hints InsertIdle .* rust-analyzer-inlay-hints
        hook -once -always window WinSetOption filetype=.* %{
            remove-hooks window rust-inlay-hints
        }
    }

    hook global KakEnd .* lsp-exit
}
```
The readme has the startup code as
```kak
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
},
```
but when I add the `eval` line, I get an error message about the `lsp-start` command already being defined, and the linked wiki page about configuration with `plug.kak` says that `lsp-enable-window` takes care of it anyway.

When I open a Rust file with this configuration, I can tell that the language server is working in some capacity because I get the warning and error markings in the left margin and I can do things like list all errors and lsp capabilities. But I get no inlay hints or hover functionality, “go to definition” doesn’t work, and “show code actions” shows nothing. I have been completely unable to diagnose the problem.

**Comment by ul** [comment]
What you have in the first listing should be enough as, iirc, plug.kak sources `lsp.kak` automatically, when you do `eval` you essentially request it again from kak-lsp. I believe @andreyorst can provide a better explanation of how to configure kak-lsp with plug.kak.

**Comment by andreyorst** [comment]
correct, plug,kak loads all scripts automatically, so you don't need to use
eval part

пн, 15 июн. 2020 г., 07:35 Ruslan Prokopchuk <notifications@github.com>:

**Comment by andreyorst** [comment]
[here's my config](https://gitlab.com/andreyorst/dotfiles/-/blob/81119be8a0382f79297bfb33f4bcc158aa735444/.config/kak/plugins.kak#L89-112). Note that I start lsp with `lsp-enable-window` command in a filetype hook inside `config` block

**Comment by loewenheim** [comment]
> [here's my config](https://gitlab.com/andreyorst/dotfiles/-/blob/81119be8a0382f79297bfb33f4bcc158aa735444/.config/kak/plugins.kak#L89-112). Note that I start lsp with `lsp-enable-window` command in a filetype hook inside `config` block

I get the same result with this config.

**Comment by krobelus** [comment]
There might be a problem with `rls`, maybe a log can help:
`set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"`.

If you are usin rustup then you probably want to use `rustup which rls`; this is the current default config:

```toml
[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "sh"
args = ["-c", "if command -v rustup >/dev/null; then $(rustup which rls); else rls; fi"]
```

**Comment by loewenheim** [comment]
This seems to have gone away upon reinstalling `rls`.
