### ISSUE TITLE
How to automate lsp-code-actions

### ISSUE THREAD

**Issue by eikenb** [kak-lsp/kak-lsp#367]
I'm trying to add a hook to have kak-lsp + gopls automatically update the imports section on save. It all works except I can't figure out a way to automate the final step of hitting 'Enter' on the 'Organize Imports' code-actions menu.

What is the intended way of automating this?

Thanks.

**Comment by krobelus** [comment]
for this specific task you can pipe the buffer through `goimports` on save (instead of `gofmt`)

**Comment by eikenb** [comment]
Yes. And I have done that in the past. I'm trying to fully utilize gopls at this time as I anticipate the goimports will be deprecated at some point. That is I am aware of that as a workaround but think it would still be good to have a means of doing this with kak-lsp.

**Comment by tadeokondrak** [comment]
Does `lsp-formatting-sync` work? I don't think code actions are meant to be scripted.

**Comment by eikenb** [comment]
`lsp-formatting-sync` only does the formatting, the language-server spec has import management as a separate activity and the gopls authors made it separate to stick with the spec.

Code actions are interactive. Eg. the "Organize Imports" only shows up in the code-actions list if the imports need changing. I think this is why they are seen as non-scripting.

I'd still like to request a way to make them script-able so they can be automated anyways where it makes sense. Ideally it would just be some way to call it such that if it would just be a noop if the action wasn't available at that time.

I have a feeling this will be a popular request once `goimports` gets deprecated as a lot of people have become used to having imports management be paired with formatting on save.

**Comment by ul** [comment]
It worth asking broader Kakoune community about automating menu selection in Kakoune, as it seems to be not a kak-lsp-specific question, and, unfortunately, my Kakoune-fu is not strong enough to answer it.

However, if it turns out to be impossible, we can make kak-lsp a little bit more flexible to support custom processing for code actions. At the moment kak-lsp server sends `menu` command directly to Kakoune. We can abstract it with something like `lsp-show-code-actions`, and then you can override this command in your config and process code actions as you wish (e.g. execute "Optimize imports" straight away without even showing menu if it's one and only available code action).

**Comment by whereswaldon** [comment]
@eikenb So I too have this issue, and I'm working around it right now by issuing `:gopls imports` manually in my BufWritePre hook. Someone appears to have implemented support for invoking `gopls` subcommands directly as a kakoune command. That being said, I agree that it would be nice to be able to automate the menu selection.

**Comment by eikenb** [comment]
You can now configure gopls to do imports formatting with the `gofumpt = true` setting.

https://github.com/golang/tools/blob/master/gopls/doc/settings.md#gofumpt-bool

**Comment by whereswaldon** [comment]
I'm trying to take advantage of that bool, but I'm not having any luck.

I've tried to combine the docs about the feature [here](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#gofumpt-bool) with the [`kak-lsp` config docs here](https://github.com/kak-lsp/kak-lsp#configuring-kakoune), and I've arrived at this:

```
set-option -add global lsp_server_configuration gopls.formatting.gofumpt=true
```

However, with that setting in effect, I see no change in behavior when I run `:lsp-formatting-sync`.

I also tried:

```
set-option -add global lsp_server_initialization_options gopls.formatting.gofumpt=true
```

No dice.
Has anyone already gotten this to work? Do you see something wrong with my approach?

**Comment by eikenb** [comment]
Sorry, I haven't tried to get it working with kak yet. I still mainly use neovim for my day to day and it works there. I'm using the latest gopls (as of a few days ago) with this configuration...

```lua
local lspconfig = require("lspconfig")
lspconfig.gopls.setup {
  codelens = { generate = true, gc_details = true },
  experimentalWorkspaceModule = true,
  semanticTokens = true,
  experimentalPostfixCompletions = true,
  gofumpt = true,
}
```

**Comment by krobelus** [comment]
I'll take a look at the gofumpt setting as soon as I get to it.
I have opened #498 to allow to define a custom function instead of the default `menu`. This is not fully fleshed out but it's easy to do.

**Comment by krobelus** [comment]
@whereswaldon Setting values like `formatting.gofumpt` dynamically is currently not possible; I've opened #500 to improve the situation. For now you can use this in your `kak-lsp.toml`

```toml
[language.go.initialization_options]
"formatting.gofumpt" = true
```
