### ISSUE TITLE
Ruby: Extra @ in the completion of attributes

### ISSUE THREAD

**Issue by alexherbo2** [kak-lsp/kak-lsp#378]
```
@▌
```

Completing `@name`:

```
@@name▌
```

**Comment by alexherbo2** [comment]
It is a general issue actually, not specific to attributes.

**Comment by krobelus** [comment]
How can I reproduce? I don't really know Ruby.

**Comment by alexherbo2** [comment]
With [Solargraph] and typing an instance variable.

[Solargraph]: https://solargraph.org

It is actually a more general issue and seems related to the completion, having `@` typed, and `@name` to complete, it expands to `@@name` instead of `@name`.

**Comment by krobelus** [comment]
OMG I finally realized the problem - it's the same as #510.
Same for `:symbol_name`. I'll fix it tomorrow.
