### ISSUE TITLE
Some explanations about using placeholders

### ISSUE THREAD

**Issue by gustavo-hms** [kak-lsp/kak-lsp#390]
Hi! First of all, thanks for this amazing work!

I see some time ago support for snippets where introduced in PR https://github.com/ul/kak-lsp/pull/270 by @topisani. Nevertheless, there's still no mention of it in the documentation (either `README.md` or the wiki), and I couldn't figure out how it is supposed to work. When I use it with [gopls](https://github.com/golang/tools/tree/master/gopls), some placeholders appear when I choose a completion suggestion, but they are not selected, and then I have to manually delete them before moving on.

I'm gonna make a small example. Suppose I have the following code:

```go
package main

type teste struct {
    um int
    umas string
}

func main() {
    t := teste{
        u|
    }
}
```
If my cursor is at the `|` position an I'm typping, the completion suggests both `um` and `umas` fields. If I then press `<c-n>` to select any of them (say, `umas`), the text `${1:},` is inserted after the completion but is not selected:

```go
    t := teste{
        umas: ${1:},|
    }
````
The cursor is positioned after the comma and the `${1:}` is not selected, making me having to manually erase everything between `umas:` and the cursor. Am I missing something?

**Comment by haarts** [comment]
I have the same issue with Dart code: #370

**Comment by ul** [comment]
I personally don't use snippets, I hope @topisani could shed some light on it.

**Comment by gustavo-hms** [comment]
Even if you don't use snippets, how do you get rid of these `${1:}` inserted on completion?

**Comment by gustavo-hms** [comment]
> Even if you don't use snippets, how do you get rid of these `${1:}` inserted on completion?

Hmm... I've just seen [here](https://github.com/kak-lsp/kak-lsp/issues/370#issuecomment-692430455) that it's a problem with a regex trying to recognise the placeholder...

The same hack used there also works for me with `gopls`.
