### ISSUE TITLE
kak-lsp not working on latest rust-analyzer

### ISSUE THREAD

**Issue by sidkshatriya** [kak-lsp/kak-lsp#392]
I'm trying to compile rust-analyzer from tip e.g. https://github.com/rust-analyzer/rust-analyzer/commit/8a21b2c96acb351baa81422f6633462b5db2298a

kak-lsp does not work and I always get "parking request" message. Could it be due to https://github.com/rust-analyzer/rust-analyzer/commit/7f79dbc84f5d69ec6f48fa8d67bdfa0525c5dd34 ? Sorry I haven't investigated further...

(kak-lsp generally works quite flawlessly for me otherwise with rust-analyzer tip)

**Comment by sidkshatriya** [comment]
Some recent fixes have improved the situation somewhat but rust-analyzer integration with kak-lsp still seems broken. As an example when trying to run an Import code action (option `a` in the kak-lsp mode) I get the following error in `*debug*` : 

(Formatted for easy readability)
```
Error: 
1:1: 'lsp-apply-workspace-edit' 
2:5: 'lsp-did-change-and-then' 
1:2: 'try' 2:5: 'evaluate-commands' 
1:1: 'lsp-apply-workspace-edit-request' wrong argument count
```

**Comment by sidkshatriya** [comment]
@krobelus @topisani Sorry for the ping ! I'm still facing problems with latest rust-analyzer + kak-lsp . 

Is the above error message helpful?

**Comment by sidkshatriya** [comment]
Basically I get this message whenever I'm trying to apply a rust analyzer action (e.g. a module import).

**Comment by krobelus** [comment]
Thanks for reporting, I can reproduce with an import code action.
I'm having trouble getting any log output from `rust-analyzer`, but no need I guess.
This seems to be an escaping issue in kak-lsp.

For example, when I try to apply the code action `Replace qualified path with use` on `Vec` in this file, I get the same error.
```rust
fn test() {
    // single quote '
    vec::Vec();
}
```

Whereas when I delete the single quote, it works fine.

**Comment by krobelus** [comment]
Fix for the single quote issue:

```diff
diff --git a/rc/lsp.kak b/rc/lsp.kak
index 3da06cc..e079db4 100644
--- a/rc/lsp.kak
+++ b/rc/lsp.kak
@@ -552,3 +552,5 @@ method   = "exit"
 define-command lsp-apply-workspace-edit -params 1 -hidden %{
-    lsp-did-change-and-then "lsp-apply-workspace-edit-request '%arg{1}'"
+    evaluate-commands -verbatim lsp-did-change-and-then %sh{
+        printf "lsp-apply-workspace-edit-request '%s'\n" "$(printf %s "$1" | sed "s/'/''/g")"
+    }
 }
```

I'll try to find a better fix, maybe `lsp-did-change-and-then` could accept multiple parameters, and do the escaping itself.

I suspect that there is another issue: at one point rust-analyzer kept using stale version of the file I was editing.
