### ISSUE TITLE
hover window shows files with positions that I'd like to be able to open

### ISSUE THREAD

**Issue by gspia** [kak-lsp/kak-lsp#409]
See the following pic:

![kaklsp_hs](https://user-images.githubusercontent.com/3320792/96333219-4af74500-1071-11eb-949a-a5802ef3fe2e.png)

On  a defition, the hover shows nicely the location of the documentation and source of the external lib (external to the project). In the current LPS mode there is no commands that would allow me to open a buffer/browser with those file locations. 

Is this possible or configurable at the moment?

E.g. if possible, there could be bolded/highlighted numbers 1 and 2  at the beginning of the corresponding lines, and pressing that number would allow the buffer to be opened or browser window opened. Maybe the action could even be somehow configurable.

The lsp mode has 'd', 'i' and 's' (go to definition, implementation and show function signature help) but they gave nothing here.

**Comment by krobelus** [comment]
You should be able to go-to-definition of the symbol at cursor, then the links should be nearby.
Alternatively, currently you can select the link text by holding shift+left click.
As soon as [Kakoune supports OSC 8 links](https://github.com/mawww/kakoune/issues/4316) we can add that.
Also, I think we should add an option to render the hover data into a special `*hover*` buffer, then this will be trivial.
