### ISSUE TITLE
Suggestion for portable config setup

### ISSUE THREAD

**Issue by cpdean** [kak-lsp/kak-lsp#414]
I had some trouble getting kak-lsp to switch from using clangd to ccls. No matter what config I set, it would always use clangd.  As it turns out, I naiively followed the docs and put my config in `$XDG_CONFIG_HOME/kak-lsp/kak-lsp.toml`, but because I'm on macOS, kak-lsp was looking for it in [$HOME/Library/Preferences](https://docs.rs/dirs/2.0.1/dirs/fn.config_dir.html).  Being an expert in the nuances between platforms' default config locations is something I do not aspire to, so this was new to me!  Not to mention that this means kakoune's default of putting stuff in `$XDG_CONFIG_HOME` apparently violates this norm for macOS.  Not that it matters -- now I'm angry at macOS for Thinking Different in this case.

I've decided to put my `kak-lsp.toml` in the same directory as my `kakrc` and I have changed how I add kak-lsp to my `kakrc` like this:

```
eval %sh{kak-lsp --config $kak_config/kak-lsp.toml --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|cpp) %{
    lsp-enable-window
}
```

the `%val{config}` expansion above with `$kak_config` expands to `$XDG_CONFIG_HOME/kak/`, however I believe (hope) if the end-user has done something clever to move their kakrc somewhere else (perhaps the inane `HOME/LibraryPreferences`) it will automatically adapt and point to that.  Since I do not intend to use `kak-lsp` with anything other than kakoune, colocating their config together, especially if kakoune will adapt that `$kak_config` variable to point at whatever is correct feels like it might be a useful convention to adopt.

Would this be useful in the setup documentation for kak-lsp?

**Comment by krobelus** [comment]
I agree that from a user's PoV, putting `kak-lsp.toml` in `~/.config/kak` makes sense.
Not sure what other's think?

> Would this be useful in the setup documentation for kak-lsp?

The wiki could have a tutorial, maybe even geared towards macOS. Our README is fairly dense, it should contain little more than the necessary information, but of course we can link to the wiki page.

**Comment by krobelus** [comment]
The library we use to retrieve the config dir [has changed the config dir on MacOS](https://github.com/dirs-dev/dirs-rs#changelog) from `$HOME/Library/Preferences` to `$HOME/Library/Application Support`
No worries - we haven't upgraded yet. Maybe we should still move it to ~/.config/kak, or just add an automatic migration..
