### ISSUE TITLE
Semantic highlighting stopped working with clangd-11

### ISSUE THREAD

**Issue by arrufat** [kak-lsp/kak-lsp#416]
Hi, I've been using kak-lsp together with clangd for some time now and semantic highlighting was working until today, when I upgraded from 10 to 11. Everything else works. Any one else having this problem?

Let me know if you need more information.
Thanks in advance.

**Comment by topisani** [comment]
clangd has switched from the old semantic highlighting api to the new semantic tokens api - the good news is, kak-lsp supports that as well. Make sure you're using a recent version of kak-lsp, and take a look at the readme for how to set up semantic tokens

**Comment by arrufat** [comment]
Thank you! I had already set it up for rust, but not c++. It works now!
