### ISSUE TITLE
[macOS] LSP `command` and config location override (`--config /path/to/kak-lsp.toml) only work with absolute paths

### ISSUE THREAD

**Issue by prime31** [kak-lsp/kak-lsp#423]
I'm not sure if this is by design, a bug or user error but I can only get kak-lsp working when I use absolute paths.

kakrc that works
```
eval %sh{kak-lsp --kakoune -s $kak_session --config /Users/me/.config/kak-lsp/kak-lsp.toml}
lsp-enable
```

kakrc that doesn't work
```
eval %sh{kak-lsp --kakoune -s $kak_session --config ~/.config/kak-lsp/kak-lsp.toml}
lsp-enable
```

Same goes for the kak-lsp-toml file.

kak-lsp.toml that works
```
[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "/Users/me/zig/zls/zig-cache/bin/zls"
```

kak-lsp.toml that doesn't work
```
[language.zig]
filetypes = ["zig"]
roots = ["build.zig"]
command = "~/zig/zls/zig-cache/bin/zls"
```

**Comment by krobelus** [comment]
> eval %sh{kak-lsp --kakoune -s $kak_session --config ~/.config/kak-lsp/kak-lsp.toml}

This one works fine because the shell expands `~`.

Yeah, kak-lsp.toml config values are used literally. This might be common behavior nowadays, for example in [cargo](https://github.com/rust-lang/cargo/issues/4253).

I don't have a strong opinion on whether kak-lsp should expand tildes here.
In any case, it is probably a good idea to show such fatal errors in an editor popup, currently only the log will tell you what's going on.

```
Dec 07 07:48:26.202 INFO Starting Language server `~/bin/my-language-server `, module: kak_lsp::language_server_transport:21
Dec 07 07:48:26.203 ERRO panic: panicked at 'Failed to start language server: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/language_server_transport.rs:22:21, module: kak_lsp:252
```

**Comment by prime31** [comment]
As a kak/kak-lsp newb it took a lot of time to figure out that it was the path so an error would be nice. 

As for tilda expansion, in my opinion it’s a requirement. Many people share config files online and share their own config files between different computers. It’s common practice to just pull a git repo right into ~/ especially for devs working on many computers. Not having tilda expansion means you can’t easily share the files anymore.

**Comment by krobelus** [comment]
One solution would be to put the language server binaries in `$PATH`, then you can just use `zls`.
