### ISSUE TITLE
Add support configuring rust-analyzer

### ISSUE THREAD

**Issue by Roger** [kak-lsp/kak-lsp#437]
There are a bunch of [configurations for rust analyzer](https://rust-analyzer.github.io/manual.html#configuration), that can be set using lsp messages, I guess that this can be set using `kak-lsp --request`, but I couldn't figure out what's the method or format for the configuration.

Maybe would be nice to add a configuration key in `kak-lsp.toml` that pass that to the lsp, but I still don't know if this configuration method is something standard of the protocol or if it's an adhoc method of rust-analyzer.

I found out this, since I wanted to use `rust-analyzer.cargo.loadOutDirsFromCheck` to get better completion in projects that generates code using a `build.rs` script.

**Comment by Screwtapello** [comment]
I think you may be looking for the `lsp_server_configuration` and/or `lsp_server_initialization_options` options. I haven't tested it myself, but something like:

    set-option global lsp_server_initialization_options rust-analyzer.cargo.loadOutDirsFromCheck="true"

...might be what you want.

**Comment by krobelus** [comment]
You can add this to `kak-lsp.toml` with a snippet like this (something similar is in the default config for rust-analyzer actually).

```
[language.rust.initialization_options]
cargo.loadOutDirsFromCheck = true
```

`lsp_server_initialization_options` can be used to override that dynamically.

**Comment by Roger** [comment]
Thanks! that worked, didn't realize that was added to the default `kak-lsp.toml` how to configure rust-analyzer
