### ISSUE TITLE
[Feature Request] Different display for docs

### ISSUE THREAD

**Issue by clad26** [kak-lsp/kak-lsp#446]
I primarily work in the julia language and use its LS via kak-lsp. The most helpful feature for me is the docs using lsp-hover. But its almost useless to do that in kakoune using kak-lsp as:

1. The docs cover the entire screen and are still not fully displayed
2. They involve a lot of markdown, which don't get rendered, so what we see is a mess.

The solution I suggest would be:
A box above the cursor, which has the docs with rendered markdown and is scrollable!

It'd be great if kak-lsp can have its own display for docstrings, and not use kakoune's info boxes for that.
It can be implemented with something like [termimad](https://github.com/Canop/termimad)(in Rust) or [glow](https://github.com/charmbracelet/glow/)(in Go), especially for scrollable rendered markdown in lsp-hover

Is it possible? 
The docs are one of the most important features of LanguageServers. Having a proper implementation is a necessary feature and the info boxes are not cutting it.

**Comment by clad26** [comment]
In short, is it possible to re-implement hover from kak-lsp, to give the above-suggested output?

**Comment by krobelus** [comment]
Maybe we shoud offer commands to render help in `%opt{docsclient}`

**Comment by clad26** [comment]
Any image of how %opt{docsclient} works？
Also, can it render markdown？

**Comment by clad26** [comment]
@krobelus I can't seem to get how :doc works
I'd appreciate it if you can tell me a command to make :doc do something

**Comment by krobelus** [comment]
Start with `kak -e 'doc doc'`

**Comment by clad26** [comment]
@krobelus Thanks!!!
But... how do we use it with a language while editing in normal mode?

**Comment by clad26** [comment]
Is there any way to open this buffer in the lower corner of the window?
fzf.kak would help!!! But the page says its not correctly maintained.....

**Comment by clad26** [comment]
@krobelus I've two questions, I'd appreciate it if you can answer them...😅
1. Is info a buffer like doc too?
2. Can we use your approach to get this too?
![Screenshot from 2021-02-03 01-32-02](https://user-images.githubusercontent.com/51269425/106656366-9c93f300-65c0-11eb-9956-58500d7e95c9.png)
