### ISSUE TITLE
Can't understand of two remap SnippetsNextPlaceholders and SnippetsOtherPlaceholders

### ISSUE THREAD

**Issue by egolep** [kak-lsp/kak-lsp#450]
I saw in the README the part regarding snippets, but now I'm stucked with Ctrl-n for SnippetsNextPlaceholders and Ctrl-p for SnippetsOtherPlaceholders.
I also noticed that, even if I don't even have a snippet_support = true line anywhere in my kakrc, I stll get snippet support (aka: snippets appears and I can move between them with the aforementioned keybindings).
Am I missing something? I tried to use the script provided in the README itself, but it simply changes nothing.

Forgive me for my noobiness

**Comment by krobelus** [comment]
> I don't even have a snippet_support = true line anywhere in my kakrc

that needs to go into your kak-lsp.toml.

Ctrl-n/Ctrl-n are default Kakoune insert mode bindings for moving to the next/previous completion. Probably what you are seeing are completions, not snippets.
