### ISSUE TITLE
No way to obtain proper rust completion

### ISSUE THREAD

**Issue by egolep** [kak-lsp/kak-lsp#451]
I tried both with rust-analyzer and rls, but I simply can't get any actual language completion. I'm stucked with only file completion (functions defined in the .rs file, already used names and words, etc).
I tried with the default and recommended ways found here and also with any kind of personal configuration found on other repos.

**Comment by krobelus** [comment]
This should work! Can you get a log when using `rls`, see https://github.com/kak-lsp/kak-lsp#troubleshooting?

**Comment by egolep** [comment]
It now works. I changed nothing. Wut?

**Comment by krobelus** [comment]
A Heisenbug!
