### ISSUE TITLE
lsp-rename does not work with pyright

### ISSUE THREAD

**Issue by ivanddm** [kak-lsp/kak-lsp#452]
I'm trying to install and configure `pyright` to use it instead of `pyls`. I have this in my `kak-lsp.toml` but still, it is not working:

```
[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "pyproject.toml", "setup.py", ".git"]
command = "pyright-langserver"
args = ["--stdio"]
offset_encoding = "utf-8"
```

**Comment by krobelus** [comment]
The log shows

```
Feb 10 17:58:38.479 ERRO panic: panicked at 'Failed to parse response: Error("invalid type: map, expected a boolean", line: 0, column: 0)', src/context.rs:127:64, module: kak_lsp:262
```

Turns out it's just because our lsp_types are outdated.
For now you can compile from the `lsp_types_86` branch, that works for me.

I'll merge that branch soon, as far as I understood I can leave the new LSP features as unsupported by just passing null in the initialization options.

**Comment by ivanddm** [comment]
I just installed branch `lsp_types_86` but still it is not working for me (with the same config as shown above).

**Comment by krobelus** [comment]
Are you sure the newly installed `kak-lsp` is first in `$PATH`?
I usually test with `PATH=target/debug/:$PATH kak`, then the binary in `target/debug/kak-lsp` (created by `cargo build`) will be used.

I'm using your config and `pyright 1.1.104-1`

**Comment by ivanddm** [comment]
I deleted the master branch and then installed the `lsp_types_86` with `plug.kak`:

```
plug "kak-lsp/kak-lsp" branch "lsp_types_86" do %{
    cargo install --locked --force --path .
} config %{...
```

I also built manually with `cargo install --locked --force --path` inside `plugins/kak-lsp` directory but still not working. This is what I get while/after building:

![image](https://user-images.githubusercontent.com/20104703/107555862-bbaa0a80-6be8-11eb-8007-ecab07d40f6b.png)

I'm using the most recent version of pyright installed with `npm install -g pyright` which is `pyright 1.1.109`

**Comment by ivanddm** [comment]
Ignore my last comment..  it is working now with this branch and config... I had forgotten to uncomment something in my `kak-lsp.toml` config 🙏🏻

**Comment by krobelus** [comment]
(I pushed the update to master and deleted the lsp_types branch.)

**Comment by ivanddm** [comment]
Everything that I normally use seems to be working (as compared to the coc-pyright), however, **renaming a symbol is not working for me**. As far as I know, `pyright` supports renaming, please correct me if I'm wrong.

**Comment by krobelus** [comment]
We send the request but get no result

```
Feb 11 23:42:42.077 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"foobar123","position":{"character":5,"line":9},"textDocument":{"uri":"file:///home/johannes/git/kak-lsp/t/a.py"}},"id":1}, module: kak_lsp::language_server_transport:183
Feb 11 23:42:42.085 DEBG From server: {"jsonrpc":"2.0","id":1,"result":null}, module: kak_lsp::language_server_transport:157
```

We could find out what other editors send.

**Comment by ebetica** [comment]
It seems like pyright also does not detect `pyrightconfig.json` properly if started through kak-lsp. I spent some time and couldn't figure out what the problem is. `pyright $filename` seems to properly detect the `pyrightconfig.json`.

**Comment by ebetica** [comment]
I have a patch here for import errors related to pyright: https://github.com/kak-lsp/kak-lsp/pull/468
