### ISSUE TITLE
lsp-highlight-references never clears highlights

### ISSUE THREAD

**Issue by sclu1034** [kak-lsp/kak-lsp#457]
`lsp-highlight-references` doesn't alter the contents of `lsp_references` when the cursor is on a token that isn't valid for highlighting (e.g. whitespace, keyword). The previous references stay active until the command is executed on another valid token.

For standalone use of the command that behavior can make sense, although a command to clear highlights without having to set a hidden option would be nice.

For use with `lsp_auto_highlight_references`, I think it would be apt if the highlights were cleared automatically when the cursor moves away from the relevant token.

**Comment by dead10ck** [comment]
Fully agree, this is a neat feature, but its utility is undercut by the fact that it can't be turned off without disabling the highlighter altogether.

**Comment by krobelus** [comment]
Yeah that seems reasonable, I'll add a fix.
I just tried `set global lsp_auto_highlight_references true` for the first time, it seems nice, like a fancy substitute for
`add-highlighter global/my/search_matches dynregex '%reg{/}' 0:+b`.
