### ISSUE TITLE
how to detect if lsp is enabled?

### ISSUE THREAD

**Issue by basbebe** [kak-lsp/kak-lsp#461]
Say I wanted to automatically format and lint on file operations for several filetypes.
Depending on the machine, I could have lsp configured or not.

To integrate this logic, how would I find out if lsp is enabled and/or running?

**Comment by krobelus** [comment]
You can check if lsp is loaded with something like this

```
try %{
    nop %opt{lsp_cmd}
    echo using lsp
} catch %{
    echo no lsp
}
```

As for checking if it is enabled, I'm not sure if there's a proper way yet. You can use the same hack that `lsp-enable` uses:

```
try %{
    add-highlighter global/lsp_references ranges lsp_references
    echo lsp is not enabled globally
    remove-highlighter global/lsp_references # clean up
} catch %{
    echo lsp is enabled globally
}
```

**Comment by basbebe** [comment]
Thanks.

Would be great if there was a way, like an option that was set by lsp if it was enabled.
