### ISSUE TITLE
Update wiki entry on C, C++ language servers

### ISSUE THREAD

**Issue by muffin4** [kak-lsp/kak-lsp#465]
In [release v9.0.0](https://github.com/kak-lsp/kak-lsp/releases/tag/v9.0.0) the default language server for C and C++ was changed from cquery to clangd. This change is now yet reflected on the [related wiki page](https://github.com/kak-lsp/kak-lsp/wiki/How-to-install-servers#c-c).

**Comment by krobelus** [comment]
Done, thanks for reporting! The wiki is world-writable, so don't hesitate to fix things there.
