### ISSUE TITLE
[Bug] Unable to rename Rust lifetimes

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#474]
Attempting to use `lsp-rename` or `lsp-rename-prompt` on a Rust lifetime specifier does not work. If you don't provide a `'` at the beginning then it will complain about it being missing. But if you do include it, something else crashes.

**To reproduce:**
- Open `kak-lsp/src/util.rs`
- Scroll to line 211
- Attempt to rename the lifetime to something else
- Observe errors

**Comment by krobelus** [comment]
works with rust-analyzer now (the `'` needs to be included), rls doesn't seem support this
