### ISSUE TITLE
Info box formatting

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#476]
I have found that in certain situations, the formatting of info boxes messes up and becomes incomprehensible. For example, calling `lsp-hover` on this method produces this:

![image](https://user-images.githubusercontent.com/3515394/114476575-b13fc900-9bb7-11eb-8ecb-734ca0f30bb1.png)

Compared to its documentation in autocomplete:

![image](https://user-images.githubusercontent.com/3515394/114476631-d2081e80-9bb7-11eb-812c-51d3ffa3d828.png)

Perhaps it's pulling plaintext for the hover, but markdown for the autocomplete? Either way, the hover version is missing several line breaks and is overall much less readable than the markdown version.

Not to mention the lack of syntax highlighting, but that's an entirely separate thing.

**Comment by krobelus** [comment]
fixed with #513
