### ISSUE TITLE
Lua language server troubleshooting

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#479]
Making this issue because [sumneko's Lua language server](https://github.com/sumneko/lua-language-server) is not responding whatsoever in kak-lsp. The original issue with it returning an invalid workspace value has been fixed, so it's not crashing anymore, but it's not doing anything else either.

I ran `kak-lsp -s PathTracer` and opened my PathTracer session, and this was all that was output:
```
rai@Tantal ~/d/p/p/Factorio-PathTracer (master)> kak-lsp -s PathTracer
Apr 20 15:19:36.262 INFO Starting main event loop, module: kak_lsp::session:28
Apr 20 15:19:48.062 INFO Starting Language server `lua-language-server -E /usr/share/lua-language-server/main.lua`, module: kak_lsp::language_server_transport:20
Apr 20 15:19:48.099 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
Apr 20 15:19:48.131 WARN Unsupported method: workspace/configuration, module: kak_lsp::controller:340
Apr 20 15:19:48.131 WARN Unsupported method: workspace/configuration, module: kak_lsp::controller:340
Apr 20 15:19:49.122 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
Apr 20 15:19:50.122 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
Apr 20 15:19:58.124 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
Apr 20 15:20:15.124 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
Apr 20 15:20:42.127 WARN Unsupported method: $/status/report, module: kak_lsp::controller:403
```

Listing the server capabilities lists all of these things:

![image](https://user-images.githubusercontent.com/3515394/115465674-30528400-a1ec-11eb-8d84-1261b12b0c2f.png)

However, absolutely nothing happens. It's as if the server doesn't exist.

AFAIK you don't need to do any pre-configuration of the server to get it to work, and I tried running it in vscode with default settings, and it worked fine. So I just have no idea what is going on.

**Comment by sclu1034** [comment]
I'm seeing this as well.
The problem seems to be `Unsupported method: workspace/configuration`. The server sends this request, then waits indefinitely for an answer.

**Comment by sclu1034** [comment]
A simple workaround is to explicitly fail the request: https://github.com/sclu1034/kak-lsp/commit/61af1dd5f65b9127f955110bb563f78f22703ce3.
It does mean that you can only run `lua-language-server` with its default configuration, but that's still better than nothing at all.

This may also apply/help in #234, which seems to be the same issue.

**Comment by raiguard** [comment]
Thank you so much! I can confirm that this is fixed, and I can finally have a language server for Lua. Bye-bye vscode!
