### ISSUE TITLE
lsp-rename: Invalid cross-device link (os error 18)

### ISSUE THREAD

**Issue by Sweenu** [kak-lsp/kak-lsp#481]
Hi,
I'm having an issue where any changes that an LSP server would make to a file other than the one I am currently editing fails with:
`Failed to apply edits to file file:///path/to/my/file (Invalid cross-device link (os error 18)), module: kak_lsp::util:194`
The error happens whether the file is in an open buffer or not.

I have nothing special about my filesystem, I'm on Archlinux, encrypted ext4 root. I really wonder where the error could come from.

**Comment by krobelus** [comment]
In `src/text_edit.rs:102` we do `std::fs::rename(&temp_path, filename)`.
`temp_path` is literally a random filename inside `/tmp/kak-lsp/your-user-name`. (we should probably use a `mktemp` here).
Is your `/tmp` (or `$TMPDIR`) on a different file system?

Maybe we should just create the temp file right next to the target file, then the rename ought to work.

**Comment by Sweenu** [comment]
I see. Well on archlinux, by default /tmp is a tmpfs partition. So that might be why then.

**Comment by krobelus** [comment]
Oh yeah, I can reproduce. Will fix shortly. How on earth did no one notice before :confused:
