### ISSUE TITLE
Remove orange highliting when code not properly formated

### ISSUE THREAD

**Issue by sucrecacao** [kak-lsp/kak-lsp#483]
Hello,

How can I remove the orange highlighting when the code is not properly formatted?
I would like to keep the `!` on the right side but have  the normal code highlighting.

Didn't found other issue related, nor explanation in the wiki and readme, I hope I didn't went through too fast.

**Comment by krobelus** [comment]
`:lsp-inline-diagnostics-disable`

The readme mentions it but of course it's not always easy to find

**Comment by sucrecacao** [comment]
Is it possible to only disable the orange one ( format error ) while keeping the red one ( compiling error ) ?

**Comment by krobelus** [comment]
Does `set-face global DiagnosticWarning normal` work?

Though you should get rid of warnings if possible ;)

**Comment by krobelus** [comment]
Oh wait, `:doc faces` says it's "default", not "normal"

**Comment by sucrecacao** [comment]
That worked perfectly, thanks!
