### ISSUE TITLE
Documentation on server configuration is unclear

### ISSUE THREAD

**Issue by gnull** [kak-lsp/kak-lsp#489]
The README says that we can set lsp server settings with

> ```
>  set-option global lsp_server_configuration rust.clippy_preference="on"
> ```

But how do I set multiple options? Do I need to do the same `set-option` multiple times? Or do `set-option -add`?

And the same question about `lsp_server_configuration`.

**Comment by krobelus** [comment]
> Do I need to do the same set-option multiple times? Or do set-option -add?

You can either do something like

`set-option global lsp_server_configuration foo1=bar foo2=baz`

or

```
set-option -add global lsp_server_configuration foo1=bar
set-option -add global lsp_server_configuration foo2=bar
```

**Comment by gnull** [comment]
Ah, my bad. This was in the `:help options` after all.
