### ISSUE TITLE
Support code lenses

### ISSUE THREAD

**Issue by expipiplus1** [kak-lsp/kak-lsp#490]
see: https://vscode.rocks/codelens/

It would be great to be able to use code-lenses in kakoune!

In nvim they're rendered as "virtual text" hanging off the end of lines.

![image](https://user-images.githubusercontent.com/857308/120261309-3ac36b80-c2ca-11eb-9bd5-e4b059c58cff.png)

**Comment by expipiplus1** [comment]
See here for a discussion on virtual text: https://github.com/mawww/kakoune/issues/1813

**Comment by krobelus** [comment]
added as of ab07f913 (Support LSP code lenses, 2022-04-28)

**Comment by expipiplus1** [comment]
Wow, thanks!

**Comment by Rotaerk** [comment]
This doesn't seem to work.  Using v12.2.0, when I run the `lsp-code-lens` command (or type `,ll`), with the cursor on the line marked by `>`, I get an empty `lsp-menu-select` menu.

This used to work.  On April 28th, the head of your code-lens branch was commit d7fb3b56a85c21299838c414d2379fa6ad28ed1c.  (This doesn't appear to be in your branch history, but it can be directly checked out.)  While the unicode gutter character you had at that time caused issues, the `lsp-code-lens` command itself worked.

**Comment by krobelus** [comment]
My bad I should have added a test. Fixed as of ed1fb46a7ce0821e11ad96da31b12b917dbdb245

**Comment by Rotaerk** [comment]
Yep, that works for me.  Thanks for the quick fix!
