### ISSUE TITLE
Inlay hints for Rust variable declarations are one character off

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#493]
![image](https://user-images.githubusercontent.com/3515394/121818122-85d26c80-cc42-11eb-95c0-45d4b881d6f8.png)

As you can see, the inlay hints for `args` and `directory` are one character off. This used to happen occasionally, but then it would fix itself. Now it's been happening consistently for the past few weeks with no end in sight.

Argument name hints appear to work just fine.

**Comment by clarfonthey** [comment]
Also getting this as well. It feels a bit confusing since it looks like I made the mistake, not the inlay.

**Comment by vbauerster** [comment]
Do you get this on master version of kakoune?
This bug appeared for me when I had `show-whitespaces` highlighter enabled, but it was fixed:
https://github.com/mawww/kakoune/issues/4052

**Comment by clarfonthey** [comment]
It appears to be so.

Release:
![Screenshot from 2021-07-26 13-49-33](https://user-images.githubusercontent.com/15850505/127035959-59ef5648-efd5-4719-b897-99d390b3398a.png)

Git:
![Screenshot from 2021-07-26 13-56-06](https://user-images.githubusercontent.com/15850505/127035977-d80a2f63-8bc4-4eab-a114-cfc7749b721c.png)

(apparently, it also affects my custom colour scheme, but I'll fix that later)

**Comment by raiguard** [comment]
Guess it's time to start building kak from source instead of using the AUR. I'll let you know what I find.

**Comment by raiguard** [comment]
Oh, nice! Thanks for the tip.

**Comment by raiguard** [comment]
Yep, can confirm that updating to master fixes this. I guess this is an upstream issue!
