### ISSUE TITLE
Clicking on links in the info windows

### ISSUE THREAD

**Issue by sidkshatriya** [kak-lsp/kak-lsp#495]
kak-lsp will occasionally show me links in info windows. e.g. "For further information see documentation file:///abc/123/xyz.html"

I want to be able to navigate to those links. When I position my mouse on these links, it is automatically underlined but clicking on it does not result in any action.

I'm guessing this is not really related to kak-lsp _per se_ but this seems to be a common enough scenario that hopefully some of you have encountered this and have suggestions?

**Comment by malte-v** [comment]
You'll need to tell your terminal how to open these links. This doesn't have anything to do with kak-lsp.

**Comment by sidkshatriya** [comment]
Thanks, I'll try to figure this out. Yes I agree that this does not have anything to do with kak-lsp.

**Comment by sidkshatriya** [comment]
BTW If you're using tmux, I found this useful https://github.com/tmux-plugins/tmux-urlview
