### ISSUE TITLE
lsp-rename failing when renaming file outside of current buffer (NOT the same as #481 (i think))

### ISSUE THREAD

**Issue by loovjo** [kak-lsp/kak-lsp#499]
Hello,

Using kak-lsp version 10.0.0-snapshot and `python-lsp-server` with the `rope` extension (`pip3 install 'python-lsp-server[rope]'`) I get an issue when trying to use `:lsp-rename` where there exist references to the renamee outside of the current buffer.

The error I get is the following:

```
ERRO Failed to apply edits to file file:///private/tmp/y.py (Text edit range points past end of line.), module: kak_lsp::util:191
```

Here, `y.py` is the file containing a reference to the symbol being renamed.

Here is a minimal example that triggers the behaviour for me:

x.py:

```py
class Hello:
    def blah():
        pass
```

y.py

```
from x import Hello

Hello().blah()
```

Having the main cursor on the `Hello` in `x.py`, doing `:lsp-rename-prompt` and renaming it to, say, `Hellowo` triggers the error. Note that all renaming in the active buffer succeeds.

Attached is the kak-lsp.log file (with some personal information redacted).

[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/6807531/kak-lsp.log)

**Comment by krobelus** [comment]
Should be fixed. Thanks for the detailed report, much appreciated!
