### ISSUE TITLE
Weird behavior when autocompleting

### ISSUE THREAD

**Issue by snakedye** [kak-lsp/kak-lsp#503]
Examples

![image](https://user-images.githubusercontent.com/49378990/127238622-1f4722fa-7a17-4a94-a064-5320f25ee263.png)

Why do I have those highlighted zones when I don't fill an autocomplete field with autocomplete? Is there a way to disable that because it constantly causes me to jump around in the buffer for no reason.

**Comment by krobelus** [comment]
Try disabling snippet support with `snippet_support = False` in your `kak-lsp.toml`.
 a0cc198fbd1c49c75b658e27ec76ff5bb8983d94 already does that on latest master.

**Comment by krobelus** [comment]
Assuming this is answered but please speak up otherwise

**Comment by krobelus** [comment]
Duplicate of #282

**Comment by snakedye** [comment]
Left it open to see if the behavior itself would be corrected or improved. Disabling it was just a momentary workaround from my pov.

**Comment by krobelus** [comment]
Yeah I should have linked the main snippet/completion issue in the first place
