### ISSUE TITLE
runaway processes

### ISSUE THREAD

**Issue by BrianHicks** [kak-lsp/kak-lsp#506]
Hey there! I've tried to use kak-lsp a couple of times and have had a consistent problem: if I use it for a little bit, it starts spawning a ton of processes, which blocks any other process from starting in the shell while it's happening (presumably because of ulimit stuff?) This makes it hard to actually gauge what's going on!

This most recent time I've tried kak-lsp by starting it in the foreground in a shell in verbose mode. Unfortunately, I didn't see anything unusual happening, but maybe I don't know what to actually look for either. I can make and attach a log if it'd be helpful—but I'm not sure if it *would* be helpful so I'm not going to by default.

Do you have any idea what could be happening here, and how I could fix it? I've searched the issues and looked over the README and wiki and didn't see anything immediately relevant.

This has happened with both language servers I've tried (rust-analyzer and elm-language-server) and I'm on the v10.0.0 release tag of kak-lsp and Kakoune v2020.09.01.

**Comment by krobelus** [comment]
> I use it for a little bit

How long does that usually take? If it takes a while, that'll make it harder
to get to the bottom of this :(

(When using rust-analyzer, on startup a few rust-analyzer processes will
index the project for a bit. But your issue sounds different.)

> it starts spawning a ton of processes which blocks any other process
> from starting in the shell while it's happening (presumably because of
> ulimit stuff?) 

I assume those are kak-lsp processes? So not language servers?

Are they maxing out your CPU, or just idling? Any zombies?

> This makes it hard to actually gauge what's going on!

We should find a way to detect when it goes bad, and automatically kill
kak-lsp when that happens. Not sure what's the best way to do that?
Set ulimit to something really low? Start kak-lsp with `timeout -s9` by
adding that as prefix to `%opt{lsp_cmd}`?

Once we have that, it should be easier to find a minimal config to reproduce.

Either way please try it with no config:

	HOME=$(mktemp -d) kak -e '
		eval %sh{kak-lsp --kakoune -s $kak_session}
		set global lsp_cmd "kak-lsp -s %val{session} -vvvv --log /tmp/kak-lsp.log"
		lsp-enable
	'

> This most recent time I've tried kak-lsp by starting it in the foreground

Did the issue also happen here?

> Unfortunately, I didn't see anything unusual happening

When I run with `-vvvv` in my `%opt{lsp_cmd}`, I get lots of log messages,
but only whenever I switch buffer, edit a buffer, or do something lsp-related, like `gd`.
When you are idling or just moving around a single buffer, there should be nothing
added to the logs.

Does it also happen on a minimal Rust project (`cargo init tmp-project`)?

**Comment by BrianHicks** [comment]
> How long does that usually take?

Shortly after startup. I haven't found a behavior that reliably triggers it yet, but it's pretty quick regardless.

> I assume those are kak-lsp processes? So not language servers?
>
> Are they maxing out your CPU, or just idling? Any zombies?

It's a mix of kak-lsp and kak processes. I've been in recovery mode when it's happened before, so I haven't noted CPU usage or zombie-ness. I'll note that when I'm trying to reproduce.

---

As to the rest of your message, I'll use those as reproduction instructions and try to reproduce it this week sometime! Thank you!

**Comment by krobelus** [comment]
What a coincidence: today when I upgraded kak-lsp to an incompatible version I noticed that I had 2700(!) `kak-lsp --request` processes sitting around doing nothing. My guess is that in my case the old server was still alive, so new requests would go hit a dead end. I can recreate that but it's probably unrelated. Still, we might be able to improve error messages.

> It's a mix of kak-lsp and kak processes

kak-lsp shouldn't spawn any kak processes, so their number should be small.

A log might be helpful because it can tell us if there are requests that never finish.

**Comment by BrianHicks** [comment]
Just to follow up: I finally got around to trying to reproduce this with a minimal project and I can't. 😞  I'm going to keep trying periodically. If it'd be helpful for you to close this issue, feel free!

**Comment by BrianHicks** [comment]
OK, after messing around with it a bit more I think I figured out what was going on: I had a hook that ran `rustfmt` before saving each time. I think that might have been looping forever with something in kak-lsp because once I removed it the problem went away.

Here's the diff that fixed it: https://git.bytes.zone/brian/dotfiles.nix/commit/f4d147ebbc2646bb064041ab582649edabefe3d5

Buuuut, I admit that I'm guessing here! With you knowledge of how the system actually works, does it seem like a reasonable explanation or am I just getting lucky here?

**Comment by krobelus** [comment]
Hmm that shouldn't be a problem. I use a similar BufWritePre hook with `clang-format` and `gofmt`, I'll try with `rustfmt` now too.

Did you also use a hook with elm-language-server?

>  I think that might have been looping forever with something in kak-lsp

That's strange. If I `tail -f` the log, I just get `textDocument/didSave` + `textDocument/didChange` on save. The latter is only sent when the file was actually changed.

**Comment by BrianHicks** [comment]
As a matter of fact, it happened again, but I haven't had a chance to get back to the issue to report that back! Meetings today! 

I used a similar hook with elm-language-server and elm-format, yes.

The next thing I've tried was disabling inlay hints and semantic tokens. I also disabled the `InsertIdle` completion command since I don't care enough about completions to pay the price of rust-analyzer running clippy and compiling on (what seemed like) every keystroke. 😵 That seems to have gotten me into a stabler place.

**Comment by krobelus** [comment]
> I also disabled the InsertIdle completion command since I don't care enough about completions to pay the price of rust-analyzer running clippy and compiling on (what seemed like) every keystroke. dizzy_face

Right, the default idle timeout is 50ms, which will basically trigger on every keystroke. I personally haven't really noticed problems with that but #394 tracks how we can improve the idle timeout in a nice way short of just disabling them with
`define-command -override lsp-completion %{}`
I'd love to find a solution that is on by default (not another config option)

**Comment by BrianHicks** [comment]
mmhmm, I saw that one, so I didn't open another issue. (I did subscribe, though!)

For now, my solution is to just opt out of completions. That's working pretty well for me, so far!
