### ISSUE TITLE
I can't run kak-lsp as of d5e39a9

### ISSUE THREAD

**Issue by arrufat** [kak-lsp/kak-lsp#512]
After updating to https://github.com/kak-lsp/kak-lsp/commit/d5e39a9effe789b7bb7587681382fdb71b5c1f0b, I get the following error:
```
*** This is the debug buffer, where debug info will be written ***
/home/adria/.config/kak/kakrc:140:1: 'eval': 52:1: 'add-highlighter': no such id: 'kakrc'
/usr/share/kak/kakrc:29:1: 'evaluate-commands': 129:1: 'source': 140:1: 'eval': 52:1: 'add-highlighter': no such id: 'kakrc'
error while parsing kakrc:
    1:1: 'source': 29:1: 'evaluate-commands': 129:1: 'source': 140:1: 'eval': 52:1: 'add-highlighter': no such id: 'kakrc'
```
It was working  before. I noticed that there were some configuration changes, so I now just have this line in my `kakrc` (no `kak-lsp.toml`) which is enough to trigger the error.

``` kak
eval %sh{kak-lsp --kakoune -s $kak_session}
```

Do I have to do something else?

**Comment by kkga** [comment]
Same issue. My guess is that something in https://github.com/kak-lsp/kak-lsp/commit/d9410e4d7f5aa34619ca4d46d533a9c09f55d0cb is causing the error.
