### ISSUE TITLE
Jump-to buffers are generated with a wrong path

### ISSUE THREAD

**Issue by Glaeqen** [kak-lsp/kak-lsp#517]
*goto*, *symbols* etc. buffers that are generated with `lsp-references` or `lsp-document-symbol` etc. generate file paths against the project root. If kakoune workspace directory is different, links seize to work :/

If that's relevant, this is the case for rust-analyzer 2021-09-06 and kak-lsp v.11

I didn't find an existing issue for it. If I missed it, sorry for a duplicate :)

**Comment by krobelus** [comment]
Well this was embarassing.
I've been using some local overrides to solve this problem in a different way,
so I never actually noticed.

Fixed now - the paths are still always created relative to the project root;
only when jumping we might need to make them absolute.
