### ISSUE TITLE
Question: What is `default+d` and what does it do?

### ISSUE THREAD

**Issue by xnuk** [kak-lsp/kak-lsp#520]
https://github.com/kak-lsp/kak-lsp/blob/0cb48a0eacd582f45e9e62642cda5a286ac603d8/kak-lsp.toml#L354

**Comment by caksoylar** [comment]
It is a Kakoune face definition, see `:doc faces` in kak. `default` is the default face and `+d` means apply "dim" attribute to it, which should show it as slighly dimmer than regular text.
