### ISSUE TITLE
rust-analyzer "replace match with if let" code action doesn't apply correctly

### ISSUE THREAD

**Issue by sclu1034** [kak-lsp/kak-lsp#527]
This time I do have a reproducible setup:

```rust
enum Test {
    Foo,
    Bar,
}

fn main() {
    let foo = Test::Foo;
    match foo {
        Test::Foo => println!("foo"),
        _ => {}
    }
}
```

Put the cursor somewhere in the `match` block and execute the code action.

The resutling block will be

```rust
    ifet Test::Foo = foo {
        println::! ("foo")
    }
```

Commands sent by kak-lsp:
```kak
set-register s %val{selections_desc}
eval -buffer ''/tmp/rust-test/src/main.rs'' -save-regs ^ ''select 8.5,8.9 8.11,8.13 8.14,8.14 9.9,9.12 9.13,9.14 9.15,9.17 9.18,9.18 9.19,9.20 9.21,9.21 9.22,9.36 9.37,9.37 9.38,10.8 10.9,10.15 10.16,11.4 11.5,11.5
exec -save-regs "" Z
exec "z<space>"
lsp-replace-selection ''''if''''
exec "z1)<space>"
lsp-replace-selection ''''let''''
exec "z1)<space>"
lsp-insert-before-selection '''' ''''
exec "z1)<space>"
lsp-insert-before-selection ''''Test::Foo''''
exec "z1)<space>"
lsp-insert-before-selection '''' ''''
exec "z1)<space>"
lsp-insert-before-selection ''''=''''
exec "z1)<space>"
lsp-insert-before-selection '''' ''''
exec "z1)<space>"
lsp-insert-before-selection ''''foo''''
exec "z2)<space>"
lsp-replace-selection ''''println''''
exec "z3)<space>"
lsp-replace-selection ''''''''
exec "z3)<space>"
lsp-replace-selection ''''''''
exec "z3)<space>"
lsp-replace-selection ''''!''''
exec "z4)<space>"
lsp-replace-selection ''''("foo")''''
exec "z4)<space>"
lsp-replace-selection ''''''''
exec "z4)<space>"
lsp-replace-selection ''''''''
exec "z4)<space>"
lsp-replace-selection ''''''''
exec "z4)<space>"
lsp-replace-selection ''''
    ''''
exec "z5)<space>"
lsp-replace-selection ''''}''''
exec "z6)<space>"
lsp-replace-selection ''''''''
exec "z6)<space>"
lsp-replace-selection ''''''''''
select %reg{s}'
```

**Comment by raiguard** [comment]
I ran into this the other day as well. It was kind of hilarious just how badly it broke.

![image](https://user-images.githubusercontent.com/3515394/133948782-c69d4af7-f140-4787-b002-5f53774fae28.png)

**Comment by krobelus** [comment]
> Sort of related, but would it be possible to group all of the changes into a single undo group, instead of having to undo 50 times?

Yeah, I've been wanting to do that.
We don't get an undo group because `apply_text_edits_to_buffer` uses `eval  -buffer`, which doesn't have a client in the context. I believe that we should detect if the target file is the  same as the active buffer, and drop the `-buffer` switch in that case.

**Comment by krobelus** [comment]
I've pushed a possible fix to #532, it covers most of this example.
Sadly not everything - I ran into https://github.com/mawww/kakoune/issues/4373, I'm not sure how to work around that yet.
Probably we should move to a more robust way to perform edits.

**Comment by krobelus** [comment]
A more robust approach: apply text edits on the kak-lsp side and feed them into Kakoune with `%|cat contents-after-edits<ret>`. Then we wouldn't need to work around these peculiarities and we also wouldn't need #533.

**Comment by krobelus** [comment]
Thanks for reporting! I wish there were reusable test suites for LSP clients/servers. 

I've also fixed the undo problem, this should feel more natural now.
