### ISSUE TITLE
Regression in "List document Symbols"

### ISSUE THREAD

**Issue by sidkshatriya** [kak-lsp/kak-lsp#550]
_This regression is due to an upstream issue. Specifically a change in `lsp-types` from 0.89.0 to 0.91.0_

When listing the document symbols, on current master branch:
```
src/language_features/hover.rs:11:1:SymbolKind(12) text_document_hover
src/language_features/hover.rs:27:1:SymbolKind(12) editor_hover
src/language_features/hover.rs:126:1:SymbolKind(11) PlainText
src/language_features/hover.rs:127:5:SymbolKind(12) plaintext
src/language_features/hover.rs:130:1:SymbolKind(19) impl PlainText for MarkedString
src/language_features/hover.rs:131:5:SymbolKind(12) plaintext
```

Notice: SymbolKind(XX)

**With 11.0.1** (which works correctly)

```
src/language_features/hover.rs:11:1:Function text_document_hover
src/language_features/hover.rs:27:1:Function editor_hover
src/language_features/hover.rs:121:1:Interface PlainText
src/language_features/hover.rs:122:5:Function plaintext
src/language_features/hover.rs:125:1:Object impl PlainText for MarkedString
src/language_features/hover.rs:126:5:Function plaintext
```

**Comment by sidkshatriya** [comment]
I have proposed a PR on `lsp-types` https://github.com/gluon-lang/lsp-types/pull/221

**Comment by vbauerster** [comment]
It affected completion items as well:

<img width="360" alt="Screen Shot 2021-10-31 at 17 16 57" src="https://user-images.githubusercontent.com/2206533/139582857-3da1ed41-1360-4eec-b3c8-29a02d173623.png">

**Comment by sidkshatriya** [comment]
@vbauerster Thanks -- I have addressed this issue in a subsequent commit on the same PR (i.e. https://github.com/gluon-lang/lsp-types/pull/221 )

**Comment by krobelus** [comment]
Thanks - usually I test changes for a couple of days at least but I skipped that for the lsp-types update :(
I think I'll just make our master temporarily use your PR.

**Comment by sidkshatriya** [comment]
@krobelus 
Do you intent to pin `lsp-types` to the branch or the explicit hash in `Cargo.toml` ? It might be a good idea to pin to the hash just in case there are further changes to the code on the branch... 

Thinking about this more, in general, I wonder if users of `kak-lsp` would like pulling in code for `lsp-types` from a random fork to be compiled on the fly (yours or mine or anyone else). Cargo makes this super easy but I wonder if we should avoid this for now. I for one don't like it too much if a cargo dependency is not from crates.io (or the canonical github repository for that project)...

It might be better to just wait for the PR to be merged. People who want this urgently can always do this step locally themselves.

**Comment by krobelus** [comment]
I guess Cargo.lock will show the current hash even if Cargo.toml points to a moving branch.

You're right, as long as there is no strong reason we shouldn't change repo URLs.
I wish Cargo allowed adding inline patches for such cases. Anyway, in this instance better testing or just reverting the update would have sufficed as well.
