### ISSUE TITLE
Support for call hierarchy

### ISSUE THREAD

**Issue by TeddyDD** [kak-lsp/kak-lsp#554]
It seems that [LSP 3.16](https://microsoft.github.io/language-server-protocol/specification#version_3_16_0) supports call hierarchy query. Would it be possible to support this in kak-lsp?

**Comment by krobelus** [comment]
That's an interesting feature, very powerful in theory.
See #560 for a basic implementation.

I'm not sure what the UI should look like.

Here's the buffer for outgoing calls of `InitWithCustomCA()` from https://github.com/zaquestion/lab

```
internal/gitlab/gitlab.go:107:6: InitWithCustomCA
  /usr/lib/go/src/io/ioutil/ioutil.go:36:6: ReadFile
    internal/gitlab/gitlab.go:108:24: 	caCert, err := ioutil.ReadFile(caFile)
  /usr/lib/go/src/crypto/x509/cert_pool.go:105:6: SystemCertPool
    internal/gitlab/gitlab.go:113:26: 	caCertPool, err := x509.SystemCertPool()
  /usr/lib/go/src/crypto/x509/cert_pool.go:206:20: AppendCertsFromPEM
    internal/gitlab/gitlab.go:117:13: 	caCertPool.AppendCertsFromPEM(caCert)
  /home/johannes/git/go-gitlab/gitlab.go:209:6: NewClient
    internal/gitlab/gitlab.go:138:18: 	lab, _ = gitlab.NewClient(token, gitlab.WithHTTPClient(httpClient), gitlab.WithBaseURL(host+"/api/v4"))
  /home/johannes/git/go-gitlab/client_options.go:79:6: WithHTTPClient
    internal/gitlab/gitlab.go:138:42: 	lab, _ = gitlab.NewClient(token, gitlab.WithHTTPClient(httpClient), gitlab.WithBaseURL(host+"/api/v4"))
  /home/johannes/git/go-gitlab/client_options.go:29:6: WithBaseURL
    internal/gitlab/gitlab.go:138:77: 	lab, _ = gitlab.NewClient(token, gitlab.WithHTTPClient(httpClient), gitlab.WithBaseURL(host+"/api/v4"))
```

1. The first line is the reference (in this case the caller)
2. Lines indented with two spaces are the destinations of one or more calls in that function
3. Lines indented with four spaces are their call sites

Intuitively I'd swap indentation of 2 and 3, or maybe not even show 2.

**Comment by TeddyDD** [comment]
Wow, great job 💚

> Intuitively I'd swap indentation of 2 and 3, or maybe not even show 2.

After a bit of getting used to, I think this UI works nicely. I wouldn't remove 2. Since you might want to jump to called function directly instead of call-site.

**Comment by krobelus** [comment]
Ah sorry, I used the wrong filename for incoming calls - (I used the the callee's file instead of the caller's).
Fixed now. I also made `lsp-jump` not move the cursor, that seems a bit nicer here.
