### ISSUE TITLE
Typescript server not working for node projects

### ISSUE THREAD

**Issue by eko234** [kak-lsp/kak-lsp#575]
Hi, I'm getting this error when I try to use kak-lsp on a node project, I'm being able to use kak-lsp in a react application though,
I don't know if it has something to do with the plugin, but I can't understand whats happening there, the react project has a
larger node_modules dir than the node app.

```
Dec 06 17:09:12.734 DEBG From editor: 
session  = "84281"
client   = "client0"
buffile  = "/home/jujo/aloha/api/resources/v1/user/sessions.js"
filetype = "javascript"
version  = 11
method   = "capabilities"
[params]
, module: kak_lsp::editor_transport:129
Dec 06 17:09:12.734 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_JAVASCRIPT, module: kak_lsp::project_root:58
Dec 06 17:09:12.734 INFO Found project root "/home/jujo/aloha/api" because it contains "package.json", module: kak_lsp::project_root:41
Dec 06 17:09:12.734 DEBG Routing editor request to Route { session: "84281", language: "javascript", root: "/home/jujo/aloha/api" }, module: kak_lsp::session:94
Dec 06 17:09:12.734 DEBG Language server is not initialized, parking request, module: kak_lsp::controller:99
Dec 06 17:09:12.734 DEBG To editor `84281`: eval -client client0 -verbatim -- lsp-show-error 'language server is not initialized, parking request', module: kak_lsp::editor_transport:80
```

**Comment by krobelus** [comment]
The default server for javascript is `flow` but it looks like you use `typescript-language-server`. There's also `deno`.

Anyway, all of them should work but it's hard to help without a reproducer (and I have never really touched typescript/node). We can try to set up a minimal node project -- that will probably work -- and then figure out what's the difference to your setup. typescript-language-server works fine for me on a single javscript file, so can you give more details?

There are many potential problems here: maybe it's just slow, or wrong root dir etc.

**Comment by eko234** [comment]
I think it might have something to do with the directory structure, but even when I open a single file it just doesn't work.

**Comment by eko234** [comment]
Oh sorry, I think it was because I hadn't typescript installed, seems to work now, thanks!
