### ISSUE TITLE
Query LSP from shell

### ISSUE THREAD

**Issue by TeddyDD** [kak-lsp/kak-lsp#580]
I'd like to be able to fetch information from LSP from shell.

Use case: using FZF for finding symbols etc.

Possible implementation - flag that enables printing output of `--request` to stdout instead of piping it to Kakoune

```sh
printf '
session   = "%s"
client    = "%s"
buffile   = "%s"
filetype  = "%s"
version   = %d
method    = "textDocument/signatureHelp"
[params.position]
line      = %d
column    = %d
' "${kak_session}" ... |
 eval "${kak_opt_lsp_cmd} --request-stdout | my-command"
```

**Comment by sidkshatriya** [comment]
Interesting idea. But most of kak-lsp's output is in terms of kakoune commands that only kakoune understands.

For this to be useful, kak-lsp would need to simply give you the JSON that the downstream LSP gave kak-lsp and pass it to `my-command` unaltered. 

Would that work?

**Comment by TeddyDD** [comment]
Sure, that would be even better!

**Comment by krobelus** [comment]
Sounds promising. I believe this has been brought up on Discord before.
Today you can start language servers manually in stdio mode, and input JSON-RPC (bypassing kak-lsp).
So I guess the main advantages are
1. it reuses kak-lsp language server config
2. it reuses a language server (if already running)

the design looks reasonable. It's a bit weird to input TOML and output JSON, but we can extend that (also https://github.com/kislyuk/yq is our friend)

**Comment by TeddyDD** [comment]
> It's a bit weird to input TOML and output JSON

JSON both as input and output would be preferable (since it's easy to handle JSON in shell - jq, gron, jo...) but for good start reusing `--request` format is fine as well.

**Comment by krobelus** [comment]
I have implemented a quick draft in https://github.com/kak-lsp/kak-lsp/pull/584
it should be enough to create something usable, but we can definitely polish it.
