### ISSUE TITLE
Multiple instances of rust-analyzer spawned

### ISSUE THREAD

**Issue by kirusfg** [kak-lsp/kak-lsp#597]
Whenever I go to a definition of a symbol that is located in another crate (even if the crate is a member of a workspace), kak-lsp spawns a new instance of rust-analyzer. This is not the case, say, in VS Code, where only one rust-analyzer process is used per VS Code window.

Because of that, kak-lsp is practically unusable with rust-analyzer as it uses up all my RAM. My research has yielded no information, so I am asking for assistance on this issue.

This is how I enable kak-lsp:
```
set global lsp_hover_anchor true
set global lsp_auto_show_code_actions true

hook global WinSetOption filetype=(rust|c|cpp|python|go|javascript|typescript) %{
    hook window BufWritePre .* lsp-formatting-sync
    lsp-enable-window
    # lsp-inlay-diagnostics-enable global
}
```

**Comment by krobelus** [comment]
> Whenever I go to a definition of a symbol that is located in another crate (even if the crate is a member of a workspace), kak-lsp spawns a new instance of rust-analyzer.
> This is not the case, say, in VS Code, where only one rust-analyzer process is used per VS Code window.

Right. kak-lsp behaves like nvim here because we can edit many projects (with different dependencies etc.) in a single session.

> 
> Because of that, kak-lsp is practically unusable with rust-analyzer as it uses up all my RAM. My research has yielded no information, so I am asking for assistance on this issue.

You can set KAK_LSP_FORCE_PROJECT_ROOT to use a single language server for dependencies.

(I personally haven't had a problem on my machine with 16G RAM to really need it, although I don't often go spelunking in dependent crates.)

> set global lsp_auto_show_code_actions true

I wonder if this is a relevant part of the added load. We originally disabled showing code actions by default because of lags with rust-analyzer, but I couldn't reproduce those reliably.

**Comment by kirusfg** [comment]
Thank you for a timely response!

The RAM usage is much more sufferable now. I am working on Bevy, a game engine in Rust, and there are ~20 subcrates in the workspace. Prior to setting the `KAK_LSP_FORCE_PROJECT_ROOT` option, a 1GB instance of rust-analyzer would spawn per crate, and I only have 8GB of RAM on my laptop.

kak-lsp still starts a new process for each crate outside that directory (e.g. cached crates.io dependency or std crate), but the README says the opposite:
> This avoids starting separate language servers for files outside `/my/project`

Am I misunderstanding something?

But again, the amount of RAM used is very reasonable, and those crates won't be looked up very recently anyways, so I can live with that.

------------------------------
> I wonder if this is a relevant part of the added load

Tried turning it off, there is seems to be no perceptible change in memory usage.

**Comment by krobelus** [comment]
> kak-lsp still starts a new process for each crate outside that directory (e.g. cached crates.io dependency or std crate)

That would be a bug. Not sure how you are measuring the number of processes.
I tried to reproduce it but I only ever get one log entry with `Spawning a new controller`.
Of course, kak-lsp often spawns a short-lived process, for example when you press `gd`.
But that process just forwards a message to the long-lived controller process (via the Unix socket).

> > I wonder if this is a relevant part of the added load
> Tried turning it off, there is seems to be no perceptible change in memory usage.

Thanks. Maybe we should make it the default again.

**Comment by kirusfg** [comment]
I was simply tracing the kak-lsp process via htop and its rust-analyzer children.

Sir, I swear I am not _that_ incompetent, but today, there is only one process, and I haven't even rebooted the PC :)

Again, thanks for the guidance.
