### ISSUE TITLE
Inlay diagnostics cause weird jump when selecting the newline character

### ISSUE THREAD

**Issue by krobelus** [kak-lsp/kak-lsp#604]
![image](https://user-images.githubusercontent.com/6853872/161122245-da7cd72a-9da2-48cd-92d3-b892252558f4.png)

The cursor is on `f`; when moving one character to the right it jumps over the error message and ends up after the `N`.
This is pretty jarring. I'd expect that the error message comes after the newline character

A fix probably needs a change in Kakoune.

**Comment by shapeshed** [comment]
Any pointers on this as to where this might be within Kakoune?

**Comment by krobelus** [comment]
If we do

```
nop

declare-option range-specs my_inlay_diagnostics
add-highlighter global/my_inlay_diagnostics replace-ranges my_inlay_diagnostics
define-command foo %{
    set-option global my_inlay_diagnostics %val{timestamp} '1.4,1.4| Virtual text at end of line'
}
```

`src/kak repro.kak -e 'source repro.kak'` 

we actually replace the newline character, which is not what we want.

If we change the coordinates to `1.3,1.3` we see the problem in the issue description.

Currently a limitation of replace-ranges is that it will not create newlines.
Maybe the solution is that we also prevent it from deleting newlines for the time being.

**Comment by krobelus** [comment]
or somehow enable replace-ranges to replace text beyond the newline character. That requires that it can replace zero-length ranges which currently don't really exist

**Comment by krobelus** [comment]
Fix available in the `fix-inlay-diagnostics` branch; it depends on [this Kakoune patch](https://lists.sr.ht/~mawww/kakoune/patches/48962#%3C20240128002359.1846988-2-mawww@kakoune.org%3E)

**Comment by krobelus** [comment]
fixed by https://github.com/kak-lsp/kak-lsp/pull/714
