### ISSUE TITLE
Installation instructions unclear about some things

### ISSUE THREAD

**Issue by Rotaerk** [kak-lsp/kak-lsp#614]
If you install using the [plug.kak instructions](https://github.com/kak-lsp/kak-lsp#with-plugkak), the result is that the kak-lsp repository is cloned into `%val{config}/plugins/kak-lsp`.  From here, plug.kak is able to find and load the repository's lsp.kak file.  Also part of the installation is to run `cargo install --locked --force --path .`, which seems to just add the `kak-lsp` binary to `~/.cargo/bin`.

One problem is that `~/.cargo/bin` isn't necessarily in your $PATH, so the instructions should probably indicate that's required.  Also, along these lines, the instructions say:

> You can replace `cargo install` with `ln -sf $PWD/target/release/kak-lsp ~/.local/bin/` where `~/.local/bin/` can be replaced with something in your `$PATH`.

I'm not sure what directory this is running from where $PWD makes sense, but as far as I can tell, that `target` folder is created by `cargo` during a build.  If you *replace* the `cargo install` command with the symbolic link command, as the instructions indicate, I don't think there would even be a `target` folder to link in the first place, so it seems like they're needed _together_.

Another thing that's vague is what `kak-lsp.toml` config it will use.  The instructions don't specify to copy it to `~/.config/kak-lsp/`.  Will it use the one from the repository clone in `%val{config}/plugins/kak-lsp`?

Similarly, the [from source](https://github.com/kak-lsp/kak-lsp#from-source) instructions seem to rely on `~/.cargo/bin` being in your $PATH, but don't specify this.  (Maybe this is obvious to someone who uses Rust, but to someone who doesn't, it's not obvious what `cargo install` actually does.)

Although it isn't strictly needed for installation, it may be helpful to explain _why_ the `plug.kak` approach doesn't need the `eval %sh{kak-lsp --kakoune -s $kak_session}` line in the kakrc.  Particularly, that `kak-lsp --kakoune` is actually dynamically generating a lsp.kak file, while the plug.kak approach just uses the one from the repository.

Finally, I feel the instructions to update the `kakrc` with:
```
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
lsp-enable
```
or
```
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
}
```
should be moved out of [usage instructions](https://github.com/kak-lsp/kak-lsp#usage) up into the installation instructions, as that's part of installation.

**Comment by krobelus** [comment]
Thanks for the feedback.

> If you install using the [plug.kak instructions](https://github.com/kak-lsp/kak-lsp#with-plugkak), the result is that the kak-lsp repository is cloned into `%val{config}/plugins/kak-lsp`.  From here, plug.kak is able to find and load the repository's lsp.kak file.  Also part of the installation is to run `cargo install --locked --force --path .`, which seems to just add the `kak-lsp` binary to `~/.cargo/bin`.
> 
> One problem is that `~/.cargo/bin` isn't necessarily in your $PATH, so the instructions should probably indicate that's required.

If you are installing from source, then you need to have Rust installed. If Rust was installed via [rustup](https://rustup.rs), you should already have `~/.cargo/bin` in your `$PATH`. I'm not sure about other installation mechanisms (distro-provided) but a Rust installation is much less useful without `~/.cargo/bin` in `$PATH`.

> Also, along these lines, the instructions say:
> > You can replace `cargo install` with `ln -sf $PWD/target/release/kak-lsp ~/.local/bin/` where `~/.local/bin/` can be replaced with something in your `$PATH`.
> 
> I'm not sure what directory this is running from where $PWD makes sense

plug.kak runs it inside the plugin's directory (a kak-lsp worktree)

> , but as far as I can tell, that `target` folder is created by `cargo` during a build.  If you *replace* the `cargo install` command with the symbolic link command, as the instructions indicate, I don't think there would even be a `target` folder to link in the first place, so it seems like they're needed _together_.

Good catch; if someone doesn't want to use `cargo install`, they still need to build `kak-lsp`, so this should fix it:

```diff
diff --git a/README.asciidoc b/README.asciidoc
index 6db26cdd..bf851c90 100644
--- a/README.asciidoc
+++ b/README.asciidoc
@@ -89,3 +89,3 @@ plug "kak-lsp/kak-lsp" do %{
 
-You can replace `cargo install` with `ln -sf $PWD/target/release/kak-lsp ~/.local/bin/`
+You can replace `cargo install` with `cargo build --release && ln -sf $PWD/target/release/kak-lsp ~/.local/bin/`
 where `~/.local/bin/` can be replaced with something in your `$PATH`.
```

> Another thing that's vague is what `kak-lsp.toml` config it will use.  The instructions don't specify to copy it to `~/.config/kak-lsp/`.  Will it use the one from the repository clone in `%val{config}/plugins/kak-lsp`?

I think the first paragraph in https://github.com/kak-lsp/kak-lsp#configuring-kak-lsp talks about that.
There is exactly one config file location, but if it doesn't exist, it uses sensible defaults (maybe we can clarify the latter part).

> 
> Similarly, the [from source](https://github.com/kak-lsp/kak-lsp#from-source) instructions seem to rely on `~/.cargo/bin` being in your $PATH, but don't specify this.  (Maybe this is obvious to someone who uses Rust, but to someone who doesn't, it's not obvious what `cargo install` actually does.)

Right, we should probably clarify this to users who are unfamiliar with `cargo`.

> 
> Although it isn't strictly needed for installation, it may be helpful to explain _why_ the `plug.kak` approach doesn't need the `eval %sh{kak-lsp --kakoune -s $kak_session}` line in the kakrc.  Particularly, that `kak-lsp --kakoune` is actually dynamically generating a lsp.kak file, while the plug.kak approach just uses the one from the repository.

Sure, I guess. We could also make it so that repeated loading doesn't throw errors, then we can lose the distinction...

> 
> Finally, I feel the instructions to update the `kakrc` with:
> ```
> eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
> lsp-enable
> ```
> or
> ```
> eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
> hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
>     lsp-enable-window
> }
> ```
> should be moved out of [usage instructions](https://github.com/kak-lsp/kak-lsp#usage) up into the installation instructions, as that's part of installation.

Right, this was brought up before in https://github.com/kak-lsp/kak-lsp/discussions/601
I've made an attempt to improve it on https://github.com/kak-lsp/kak-lsp/tree/docs how does that look?

**Comment by Rotaerk** [comment]
Definitely an improvement!

Regarding the assumption of `~/.cargo/bin` being in your path:  That may be setup automatically by the `rustup` tool you mentioned, but as you speculated, it's not always the case with other methods of installing cargo.  For instance, installing cargo through Nix didn't add `~/.cargo/bin` to my PATH.  Maybe that's a defect in Nixpkgs, though, and maybe such situations should be treated as "non-standard" and out of scope of the instructions.  On the other hand I don't think it'd hurt to mention the fact that `cargo install` leaves kak-lsp in `~/.cargo/bin` and that the rest of the instructions depend on that being in your PATH.

Regarding which kak.lsp is used in the plug.kak scenario, the "Configuring kak-lsp" section does indeed make it clear *where* it will look for kak.lsp, particularly in `~/.config/kak-lsp` (where `~/.config` might be something else on some OSes).  However, it doesn't make it clear how it gets there.  The "From Source" instructions as well as the "Linux - Others" instructions both provide steps to copy the kak.lsp into that config folder, from the git clone and from the tar.gz respectively.  However, the plug.kak instructions provide no such steps, so the kak.lsp file just won't be there.

Aside from those things, it looks good to me.
