### ISSUE TITLE
Can't use autocompletions 

### ISSUE THREAD

**Issue by 0rphee** [kak-lsp/kak-lsp#624]
It may be a dumb question, but I just managed to enable kak-lsp and haskell-language-server, yet, I can't use the lsp's autocompletion, I've tried to use them with tab, with space, and with the arrows, but I can't do it? 

https://user-images.githubusercontent.com/79347623/177055529-e78f98d3-713b-487a-bd35-c62d9500827d.mov

Could it be due to an incorrect configuration? what can I do? 
Thank you in advance!

**Comment by krobelus** [comment]
Try `<c-n>` and `<c-p>` ;)
See also `:doc keys insert-mode-completion`

**Comment by 0rphee** [comment]
Oh thank you!
On other note, I was a little confused by the `<c-n>` notation, I hadn't seen anywhere else before haha, maybe it would be nice to add a note about it in the readme? 

Anyways, it may be just me, thanks!

**Comment by krobelus** [comment]
That notation is Kakoune convention; `:doc keys` explains it, I think plugins shouldn't need to repeat that information.
