### ISSUE TITLE
Python language server doesn''t support method textDocument/semanticTokens/full

### ISSUE THREAD

**Issue by altunyurt** [kak-lsp/kak-lsp#625]
I've recently updated kak-lsp (b29989a) and trying it with pyright over the configuration below: 

```yaml
[language.python]     
filetypes = ["python"]                           
roots = ["requirements.txt", "setup.py", ".git", ".hg"]            
command = "pyright-langserver"                                                                     
args=["--stdio"]                                 
```

I get the following errors from the language server: 

```log
Jul 07 11:54:38.638 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_PYTHON, module: kak_lsp::project_root:58
Jul 07 11:54:38.638 DEBG Routing editor request to Route { session: "1229487", language: "python", root: "/home/den/calisma/python/araci" }, module: kak_lsp::session:94
Jul 07 11:54:38.638 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/den/calisma/python/araci/main.py"}},"id":4}, module: kak
_lsp::language_server_transport:182              
Jul 07 11:54:38.640 DEBG From server: {"jsonrpc":"2.0","id":4,"error":{"code":-32601,"message":"Unhandled method textDocument/semanticTokens/full"}}, module: kak_lsp::language_server_transport:156
Jul 07 11:54:38.640 ERRO Error response from server: Failure { jsonrpc: Some(V2), error: Error { code: MethodNotFound, message: "Unhandled method textDocument/semanticTokens/full", data: None }, id: 
Num(4) }, module: kak_lsp::controller:169        
Jul 07 11:54:38.640 DEBG To editor `1229487`: lsp-show-error 'python language server doesn''t support method textDocument/semanticTokens/full', module: kak_lsp::editor_transport:84
```
Trying with palantir's and microsoft's python-language-server packages spits out the similar errors about "textDocument/semanticTokens/full" method too.

**Comment by krobelus** [comment]
Ok I can reproduce.

Curiously, `lsp-show-error` will not show the info box here (so it's only visible in the `*debug*` buffer) because `lsp-semantic-tokens` does not pass the client context.

I guess we should not send unsupported requests to the server, like b29989a does for the lsp-auto-* requests.
And perhaps add a debug log entry like `"Server does not support textDocument/semanticTokens/full, refusing to send request"`.

**Comment by krobelus** [comment]
how did you notice BTW? only by looking at logs?

**Comment by altunyurt** [comment]
Yes, nothing special other than watching logs. I was trying to get it working with pyright, which i haven't been able to do yet, that's why i turned on debug logging.

**Comment by krobelus** [comment]
your pyright config works fine for me, do you have steps to reproduce?

**Comment by altunyurt** [comment]
Turns out that it was due to some other mistake i made in kak-lsp configuration. Everything works fine now. But at least it helped fixing another issue :)  Thanks for the help and for this awesome plugin.
