### ISSUE TITLE
Godot - GDScript completion on save produces unexpected diagnostic errors

### ISSUE THREAD

**Issue by razcore-rad** [kak-lsp/kak-lsp#629]
Following the instructions from the wiki, we set up the `kak-lsp` - Godot communication through `netcat`:

```
[language.gdscript]
filetypes = ["gd", "gdscript"]
roots = [".import"]
command = "nc"
args = ["localhost", "6008"]
```

The following error diagnostic is produced on save only: `DBG.gd:1:1: error: Unexpected token: Identifier:Null` (for Godot v3.5).

I talked with someone that worked on the Godot LSP and they mentioned that Godot has `"includeText"` set to `true` and that the messages sent to the server should include the `"text"` entry.

This doesn't happen on `"textDocument/didSave"`:
```
Jul 20 19:01:38.655 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/razcore-rad/Projects/code/razcore-rad/godot-3-dbg/DBG.gd"}}}, module: kak_lsp::language_server_transport:182
```

My understanding is that this is the culprit.

So is there a way to force `kak-lsp` to send the `"text"` entry on `"textDocument/didSave"` as well?

For completeness' sake, I was told that Godot expects the `"text"` entry for anything that expects to use a `TextDocumentItem`, but my LSP knowledge is limited so I'm not sure what that means.

To contrast with an example that works just fine, the `"textDocument/didOpen"` which includes the `text` entry produces correct diagnostics:

```
Jul 20 19:01:14.243 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"gdscript","text":"extends Node\n\n\nfunc _ready() -> void:\n\tprint(get_filename().empty())\n","uri":"file:///home/razcore-rad/Projects/code/razcore-rad/godot-3-dbg/DBG.gd","version":1}}}, module: kak_lsp::language_server_transport:182
```

**Comment by sclu1034** [comment]
It seems that kak-lsp is indeed lacking proper handling of the [TextDocumentSyncCapability](https://docs.rs/lsp-types/latest/lsp_types/enum.TextDocumentSyncCapability.html#).

[`text_document_did_save`](https://github.com/kak-lsp/kak-lsp/blob/1c685e03388805cd29deaff35c790f871c946e2f/src/text_sync.rs#L74) would have to check `ctx.capabilities` and then set `text` accordingly.
`TextDocumentSyncKind.Incremental` seems problematic, though. We might have to retain all changes between `didSave` notifications.

**Comment by krobelus** [comment]
Yep, sounds like an easy fix.

> TextDocumentSyncKind.Incremental seems problematic, though. We might have to retain all changes between didSave notifications.

Interesting. No matter if the server requests full or incremental text sync, we currently always send the full text. See `src/text_sync.rs:50`

```rust
    let req_params = DidChangeTextDocumentParams {
        text_document: VersionedTextDocumentIdentifier {
            uri,
            version: meta.version,
        },
        content_changes: vec![TextDocumentContentChangeEvent {
            range: None,
            range_length: None,
            text: params.draft,
        }],
    };
```

I don't think this has caused any problems so far.

**Comment by sclu1034** [comment]
> we currently always send the full text

That's correct for `didChange`, the `TextDocumentSyncKind` doesn't seem to apply here.
`TextDocumentContentChangeEvent` has its own mechanism of determining "incremental" vs "full":

> If only a text is provided it is considered to be the full content of the document.

Similarly, `didClose` has no use for it, and the docs for `TextDocumentSyncKind.Incremental` state that `didOpen` should always send the full content. So `didSave` seems to be the only request where that value holds meaning.

**Comment by krobelus** [comment]
> That's correct for `didChange`, the `TextDocumentSyncKind` doesn't seem to apply here.
> `TextDocumentContentChangeEvent` has its own mechanism of determining "incremental" vs "full":
> 
> > If only a text is provided it is considered to be the full content of the document.

Yes but I think it still describes the same property, only that `TextDocumentSyncKind` is a server capability.

So I guess that if a server only supports full sync, then a client that must not send an incremental changes.
OTOH, if a server supports incremental sync, then it should be fine to send the full text.

**Comment by razcore-rad** [comment]
Thanks, that was super quick :)

**Comment by sclu1034** [comment]
> So I guess that if a server only supports full sync, then a client that must not send a incremental changes.
OTOH, if a server supports incremental sync, then it should be fine to send the full text.

I'm not so sure about that.

> Client support for `textDocument/didOpen`, `textDocument/didChange` and `textDocument/didClose` notifications is mandatory in the protocol and clients can not opt out supporting them. This includes **both full and incremental synchronization** in the `textDocument/didChange` notification.

And while it is sent as part of the capabilities, the documentation for [TextDocumentSyncKind](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSyncKind) doesn't sound like "staggered" option to me.

**Comment by krobelus** [comment]
you're right. If we want to implement this we'd need to compute a diff unles Kakoune exposes the undo history
