### ISSUE TITLE
67ce57 breaks lsp-references 

### ISSUE THREAD

**Issue by altunyurt** [kak-lsp/kak-lsp#642]
With 67ce5746261163ff2a0f655f3fb718f96cc8732a lsp-references display unrelated or wrong parts of the code.

**Comment by krobelus** [comment]
sorry about that, thanks for reporting

**Comment by altunyurt** [comment]
Thanks for the quick fix, but the same commit creates another problem. Getting back to the original file after lsp-references, i see that now there are multiple cursors in the file, all are located on the instances of the word i've looked up for the references.

**Comment by krobelus** [comment]
That's an experimental feature ;)
Helix does that for the "highlight references" request (the equivalent is mapped to `&` in kak-lsp) but I figured why not include it in lsp-references as well. Maybe it's not we should disable it if there's no toolsclient, not sure

**Comment by altunyurt** [comment]
Since one of kakoune's key points are less key strokes for the same results, I'd like to have this feature as optional, instead of default behaviour that i'd need to type an extra [,] to dispose of,  if possible :)

**Comment by krobelus** [comment]
Yeah I think I will remove it from `lsp-references` entirely since in the majority of cases the user probably wants to go back to a single selection. Should have tested it more :(

**Comment by krobelus** [comment]
fixed
