### ISSUE TITLE
select completion using tab

### ISSUE THREAD

**Issue by UltraBlackLinux** [kak-lsp/kak-lsp#647]
Hey there,
I've been trying to use the tab key to select completions, but I just can't get it to work. 
It either types out the whole mapped command or inserts a tab character.
I don't want to use <c-n> just because it's somewhat inconvenient.
How do I have to map it?
Thanks!

**Comment by krobelus** [comment]
I recommend mapping caps lock to control but of course you can use

```kak
map global insert <tab> <c-n>
map global insert <s-tab> <c-p>
```

if you want to use `<tab>` for indentation if no completion is active, then you could map/unmap in `InsertCompletionShow`/`InsertCompletionHide` hooks

**Comment by UltraBlackLinux** [comment]
Oh thank you so much!
For anyone coming across this: 
```kakscript
hook global InsertCompletionShow .* %{
	map global insert <tab> <c-n>
	map global insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
	unmap global insert <tab>
	unmap global insert <s-tab>
}
```

**Comment by krobelus** [comment]
if you have simultaneous insert mode sessions across different Kakoune clients, then you might want to use a `window`-scoped hook for each window and `window`-scoped mappings. Probably not an issue in practice.

**Comment by UltraBlackLinux** [comment]
> if you have simultaneous insert mode sessions across different Kakoune clients, then you might want to use a `window`-scoped hook for each window and `window`-scoped mappings. Probably not an issue in practice.

I'm not using kakoune for collaborative editing ;)

Still a neat feature though
