### ISSUE TITLE
highlight misalignment if line contains some non-ascii character

### ISSUE THREAD

**Issue by vbauerster** [kak-lsp/kak-lsp#652]
I've observed highlight misalignment if line contains some non-ascii character:

![Screenshot from 2022-11-29 13-40-13](https://user-images.githubusercontent.com/2206533/204481129-24b93fd2-be13-45b5-8b93-0be17e6479af.png)

Left side is kakoune with gopls, right side is helix with same gopls.
Note line [402](https://github.com/vbauerster/getparty/blob/942744b8d574f3fcab635259b7c92b8836f6ee84/getparty.go#L402) on left side with `attempt` var incorrectly highlighted. If I replace `∞` char with some ascii letter then highlight alignment is ok.

kak-lsp version is self compiled master head branch.

**Comment by vbauerster** [comment]
I've just pulled the fix, recompiled kak-lsp and still have this issue.

**Comment by krobelus** [comment]
I just tried your gopls example and I don't have the problem, before or after my fix.
Any errors in the log? Maybe it needs a specific version of gopls? I use v0.10.1

**Comment by krobelus** [comment]
actually maybe it's not fixed for you because master didn't build (I didn't have time to fix CI)
2440692f73f98e5411e650c3794135f8eee5a055 fixes the build, can you try again with latest master

**Comment by vbauerster** [comment]
> Maybe it needs a specific version of gopls? I use v0.10.1

same version here.

> actually maybe it's not fixed for you because master didn't build (I didn't have time to fix CI)

I had no problems, anyway rebuilt it again with 2440692 pulled in and have same problem.
Inspecting debug log shows that kak-lsp sends correct coordinates to editor:

```
Nov 30 17:37:25.291 DEBG To editor `432280`: evaluate-commands -client client0 -verbatim -- set-option window lsp_references 1 401.8,401.14|Reference 411.40,411.46|Reference 413.41,413.47|Reference 425.9,425.15|Reference 454.14,454.20|Reference, module: kak_lsp::editor_transport:78
```
Problematic line is [Reference 411.40,411.46](https://github.com/vbauerster/getparty/blob/9ba841bfb2b079a0d4f25e07f8ee29014cf8b8ac/getparty.go#L411).

However I'm able to reproduce with pristine `kak -n getparty.go` and then sending following to session in context:

```
evaluate-commands -client client0 %{
    set-face global Reference white,magenta
    declare-option -hidden range-specs lsp_references
    set-option window lsp_references 1 401.8,401.14|Reference 411.40,411.46|Reference 413.41,413.47|Reference 425.9,425.15|Reference 454.14,454.20|Reference,
    add-highlighter global/lsp_references ranges lsp_references
}
```

output is:
![Screenshot from 2022-11-30 23-26-07](https://user-images.githubusercontent.com/2206533/204881067-e3a95f48-ad31-480e-a48b-c817ada7c39a.png)

So maybe problem in kakoune? I use master version of kakoune.

**Comment by krobelus** [comment]
oh sorry this is likely due to wcwidth() mismatch between your OS's libc and your terminal.
See 73c2d1ab60766b0e955a66210f014bf36a902f34, https://github.com/mawww/kakoune/issues/3059 and others.
It's probably possible to work around this by LD_PRELOADing a modern wcwidth like https://github.com/ridiculousfish/widecharwidth/
Amazing how long it takes macOS to ship a modern wcwidth..

**Comment by vbauerster** [comment]
> Amazing how long it takes macOS to ship a modern wcwidth..

Actually I'm on arch linux, foot terminal with tmux.

**Comment by krobelus** [comment]
wow this may indeed be a bug in kakoune. I can reproduce with your `kak -n` steps but not with kak-lsp (even though it sends the same coordinates I think)

**Comment by vbauerster** [comment]
here is simpler reproducer:

```
kak -n -e 'eval -client client0 %{
execute-keys \%c∞,<space>word<esc>
declare-option range-specs lsp_references %val{timestamp} 1.4,1.7|Reference
set-face window Reference white,magenta
add-highlighter window/lsp_references ranges lsp_references
}'
```

**Comment by krobelus** [comment]
@vbauerster finally found the issue. You need to remove `offset_encoding = "utf-8"` from your `kak-lsp.toml`.
In general, it can't hurt to start from the default one once in a while.
We should probably make it so we ignore the `offset_encoding` parameter if the server does not seem to support it.

**Comment by krobelus** [comment]
(i could reproduce with `offset_encoding = "utf-8"`)

**Comment by krobelus** [comment]
also fixed by ce57217bb30eaef38dc524e3d7fa37b0647540c8, no need to change configuration

**Comment by vbauerster** [comment]
Indeed removing `offset_encoding = "utf-8"` fixed this problem.
Thank you very much for investing your valuable time into figuring this out.

**Comment by krobelus** [comment]
thanks for reporting!
we should have remembered to try with a default config, that would have made it easy to pinpoint the problem:

	HOME=$(mktemp -d) kak -e 'eval %sh{kak-lsp --kakoune -s $kak_session}; lsp-enable'
