### ISSUE TITLE
How to install and configure cmake-lsp

### ISSUE THREAD

**Issue by blakat360** [kak-lsp/kak-lsp#653]
Nix packages the 'cmake-language-server' package which is easy to install. However, configuring seems harder as I'm not sure how to get kakoune to recognise CmakeLists.txt files as a cmake file type. It seems that kak-lsp uses file suffixes to figure out which lsp to start and I don't want it to start the language server for all txt files.

Any help would be appreciated.

**Comment by krobelus** [comment]
> I'm not sure how to get kakoune to recognise CmakeLists.txt files as a cmake file type. It seems that kak-lsp uses file suffixes to figure out which lsp to start and I don't want it to start the language server for all txt files.

Kakoune ships a `cmake.kak`, which assigns the `cmake` filetype to cmake files.
If you type `:echo %opt{filetype}` in a CMakeLists.txt file it should print `cmake`.

kak-lsp assigns language servers based on this filetype option, so adding `filetypes = ["cmake"]` should be enough to make it work.
