### ISSUE TITLE
pylsp never gets configured

### ISSUE THREAD

**Issue by clarfonthey** [kak-lsp/kak-lsp#655]
So, I've read the logs for my own runs of `pylsp`, and I poked around on the issues for both pylsp and kak-lsp, and found this conundrum.

`pylsp` doesn't want to use `initializationOptions`, since per their comments, it's not very standardized: python-lsp/python-lsp-server#195

But from everything I can see, and my own local tests, `kak-lsp` doesn't send `workspace/configuration` unless requested, which `pylsp` never does. It would be nice to be able to ensure that the configuration is *also* sent via this, at least maybe via a config option.

Essentially, from everything I can see, pylsp isn't loading the configuration from kak-lsp since it ignores the initialization options and kak-lsp doesn't send a separate `workspace/configuration` message.

When I check the logs, I see calls for `textDocument/didOpen`, `textDocument/codeLens`, and `initialized` sent to the server, but no `workspace/configuration`.

**Comment by krobelus** [comment]
> But from everything I can see, and my own local tests, kak-lsp doesn't send workspace/configuration unless requested, which pylsp never does.

This is expected behavior, the spec says

> The workspace/configuration request is sent from the server to the client to fetch configuration settings from the client.

so we should not send this unless we're asked to.

pylsp configuration actually works fine, because we send `workspace/didChangeConfiguration` which essentially has the same information. This must be a problem in your configuration.

**Comment by krobelus** [comment]
if you see a panic in logs (search for `ERRO`) then upgrading would help if it's https://github.com/kak-lsp/kak-lsp/issues/654

**Comment by clarfonthey** [comment]
So, I saw #654 and thought it was totally separate to my case, but it might be. I thought I looked for errors in the log but this `ERRO` was sneaky:

```
Dec 04 06:58:58.451 ERRO Failed to parse header, module: kak_lsp::language_server_transport:79
```

Will use latest commit and see if that fixes it. Until then, here's the current log I have:  [.kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10148036/default.kak-lsp.log)

**Comment by clarfonthey** [comment]
Okay, the latest commit definitely adds in the `didChangeConfiguration` call, whereas the previous version I was on (14.1.0) didn't. Will let you decide if you want to keep this open or track this in the other issue, depending on whether you think they're sufficiently different. And attaching the new log:

[.kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10148040/default.kak-lsp.log)

**Comment by krobelus** [comment]
"Language server error" means pylsp terminated due to an error. Your latest log says it can't find the `flake8` module.
You explicitly asked for `flake8`, so that makes sense. You probably just need to install it.
I don't think there's a kak-lsp issue left here but LMK if otherwise

**Comment by clarfonthey** [comment]
Yeah, I'll close this. Thanks for helping with the debug since I seem to just not be able to read logs. ><
