### ISSUE TITLE
kak-lsp: Language server is not configured for filetype ``

### ISSUE THREAD

**Issue by UltraBlackLinux** [kak-lsp/kak-lsp#658]
Hey there,
I'm facing a weird issue. Whenever I open a file, I get an error saying `kak-lsp: Language server is not configured for filetype `

I checked what filetype was detected by kakoune via `:echo %opt{filetype}`  and weirdly enough it correctly reported that on whatever file I tried.

Trying to debug this I ran `:lsp-capabilities`  but this did not return anything, for whatever reason.

My config is located in .config/kak-lsp/kak-lsp.toml and I installed it via the aur (14.1.0-1) together with kakoune from the official arch mirrors (2022.10.31-1). Plug did not work with kak-lsp because of error 127 which I did not bother to look up or debug.

My kakoune config: [kakrc](https://github.com/kak-lsp/kak-lsp/files/10300311/kakrc.txt) (lines 43-46 were the only way I could get this to work, but it sadly has some drawbacks which is why I want to be able to use the kak-lsp config)

I already tried resetting the kak-lsp config which did not succeed.

Any ideas what I could do here?

**Comment by krobelus** [comment]
Does it work with the [default configuration](https://github.com/kak-lsp/kak-lsp#default-configuration)?

> I'm facing a weird issue. Whenever I open a file,

Which file? I can't reproduce without specific info

> I installed it via the aur (14.1.0-1) 

Weird, that should usually be `kak-lsp 14.1.0-snapshot`.
14.1.0 you can also get from the official repos.

**Comment by UltraBlackLinux** [comment]
> Does it work with the [default configuration](https://github.com/kak-lsp/kak-lsp#default-configuration)?

no

> Which file? I can't reproduce without specific info
any file. I tried java, I tried c++, and I even tried kakoune files. All were identified correctly.

>  14.1.0 you can also get from the official repos.

Just tried the github release build and that also didn't work

**Comment by krobelus** [comment]
> kak-lsp: Language server is not configured for filetype 

oh so I just realized that the weird thing is that it doesn't say what filetype.
Can you please paste the log file that is created by the default config command (`/tmp/kak-lsp.log`)?

**Comment by UltraBlackLinux** [comment]
[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10300373/kak-lsp.log)

I see. This even includes the file I tried.

What I Just noticed is, that it actually detected java, maybe it it showed \<accent\> whenever I switched to the debug buffer to inspect this issue? Still weird that it fails to read my java configuration.

**Comment by krobelus** [comment]
the default configuration ignores your config by overriding $HOME. That's what we want here.
Unfortunately, the default config does not support java, please show the log when you open a C file.

**Comment by UltraBlackLinux** [comment]
> the default configuration ignores your config by overriding $HOME. That's what we want here. Unfortunately, the default config does not support java, please show the log when you open a C file.

<details><summary>screenshot</summary> 
![screenshot-20221225-180750](https://user-images.githubusercontent.com/62404294/209476493-30ebd5be-5c75-42a9-8a24-2af0bde4db78.png)
</details>

Appears to be working fine. hmm
[kak-lsp.log](https://github.com/kak-lsp/kak-lsp/files/10300396/kak-lsp.log)

**Comment by UltraBlackLinux** [comment]
seems to be a config issue after all. Now with the kak-lsp log many things make more sense. I thought the debug buffer was all you'd get. Sorry. This is apparently my fault

**Comment by krobelus** [comment]
btw you probably don't want to run in ultra-verbose mode (`-vvvv`) everyday because that can produce gigabytes of logs when used heavily. Though if you're not passing a log file parameter then it's not stored anywhere so probably fine

**Comment by UltraBlackLinux** [comment]
oh okay :)
Thanks!
