### ISSUE TITLE
bash server not working. updateConfiguration failed

### ISSUE THREAD

**Issue by jogood** [kak-lsp/kak-lsp#659]
I've installed the plugin and the bash language server. The lsp plugin is enabled, but nothing is apparent (no sign of error but it doesn't seem to be working properly either). I found this error in tmp log:

```
lsp-show-message-log 'updateConfiguration: failed with [

{
"code": "invalid_type",
"expected": "object"
"received": "null",
"path": [],
"message": "Expected object, received null"
 }
]', module: kak_lsp::editor_transport:82
```

This command in shell doesn't give error: 
```
bash-language-server start
```

I'm new to kakoune. I'm using the plugin manager and lsp and that's all beside some kakoune config.

Also, I've tried to add the treesitter plugin but removed it after. But the lsp didn't seem to work before I've done that either, so I doubt it is related.

**Comment by krobelus** [comment]
This error is harmless, I see it too but everything else works fine (this probably needs a fix on the language server side, I'd need to check).

How do you tell that it's not working? You should get completions, go-to-defininition for shell functions, lsp-hover should how man pages etc.

**Comment by krobelus** [comment]
Also please post a log if it really doesn't work

**Comment by jogood** [comment]
When I do :lsp-hover, I get language server is not initialised (this is in a .sh file).

Here is what I have in :b *buffer* after opening test.sh and using :lsp-hover

`
*** This is the debug buffer, where debug info will be written ***
kak-lsp: language server is not initialized, parking request
kak-lsp: log: Initialized server v. 4.1.3 for file:///home/dude/workspace/test
kak-lsp: log: onHover 1:4 word=null
kak-lsp: log: updateConfiguration: failed with [␊  {␊    "code": "invalid_type",␊    "expected": "object",␊    "received": "null",␊    "path": [],␊    "message": "Expected object, received null"␊  }␊]
kak-lsp: log: Configuration loaded from client
kak-lsp: log: ShellCheck: running "shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/dude/workspace/test --source-path=/home/dude/workspace/test"
kak-lsp: log: BackgroundAnalysis: resolving glob "**/*@(.sh|.inc|.bash|.command)" inside "file:///home/dude/workspace/test"...
kak-lsp: log: ShellCheck: disabling linting as no executable was found at path 'shellcheck'
kak-lsp: log: BackgroundAnalysis: Glob resolved with 3 files after 0.02 seconds
kak-lsp: log: BackgroundAnalysis: Completed after 0.039 seconds.

`

Here is kak-lsp log:

`
Dec 29 14:48:32.327 INFO Starting main event loop, module: kak_lsp::session:31
Dec 29 14:48:32.327 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_BASH, module: kak_lsp::project_root:58
Dec 29 14:48:32.328 DEBG Routing editor request to Route { session: "12571", language: "bash", root: "/home/dude/workspace/test" }, module: kak_lsp::session:112
Dec 29 14:48:32.328 DEBG Spawning a new controller for Route { session: "12571", language: "bash", root: "/home/dude/workspace/test" }, module: kak_lsp::session:134
Dec 29 14:48:32.328 INFO Starting Language server `bash-language-server start`, module: kak_lsp::language_server_transport:24
Dec 29 14:48:32.329 DEBG To editor `12571`: lsp-get-config '/tmp/kak-lsp/dude/b2a3739ea272885', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.330 DEBG From editor: 
session  = "12571"
client   = "client0"
buffile  = "/home/dude/workspace/test/test.sh"
filetype = "sh"
version  = 1
method   = "textDocument/hover"

[params]

selectionDesc = "2.2,2.2"
tabstop = 4
, module: kak_lsp::editor_transport:127
Dec 29 14:48:32.330 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_BASH, module: kak_lsp::project_root:58
Dec 29 14:48:32.330 DEBG Routing editor request to Route { session: "12571", language: "bash", root: "/home/dude/workspace/test" }, module: kak_lsp::session:112
Dec 29 14:48:32.331 DEBG lsp_config:
, module: kak_lsp::settings:55
Dec 29 14:48:32.331 DEBG To editor `12571`: lsp-get-server-initialization-options '/tmp/kak-lsp/dude/8bae6a7f96164ab8', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.333 DEBG lsp_server_initialization_options:
, module: kak_lsp::settings:88
Dec 29 14:48:32.333 DEBG Language server is not initialized, parking request, module: kak_lsp::controller:112
Dec 29 14:48:32.333 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"markdown":{"parser":"kak-lsp","version":"14.1.0-snapshot"},"positionEncodings":["utf-8","utf-16"],"regularExpressions":{"engine":"Rust regex"}},"offsetEncoding":["utf-8","utf-16"],"textDocument":{"callHierarchy":{"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dynamicRegistration":false,"isPreferredSupport":false,"resolveSupport":{"properties":["edit"]}},"codeLens":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"completion":{"completionItem":{"commitCharactersSupport":false,"deprecatedSupport":false,"documentationFormat":["markdown","plaintext"],"preselectSupport":false,"resolveSupport":{"properties":["additionalTextEdits","detail","documentation"]},"snippetSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]},"contextSupport":false,"dynamicRegistration":false},"declaration":{"dynamicRegistration":false,"linkSupport":false},"definition":{"dynamicRegistration":false,"linkSupport":false},"documentHighlight":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false,"tooltipSupport":false},"documentSymbol":{"dynamicRegistration":false,"hierarchicalDocumentSymbolSupport":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["markdown","plaintext"],"dynamicRegistration":false},"implementation":{"dynamicRegistration":false,"linkSupport":false},"inlayHint":{"dynamicRegistration":false},"onTypeFormatting":{"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":true},"rangeFormatting":{"dynamicRegistration":false},"references":{"dynamicRegistration":false},"rename":{"dynamicRegistration":false,"prepareSupport":false},"selectionRange":{},"semanticTokens":{"dynamicRegistration":false,"formats":["relative"],"requests":{"full":true,"range":false},"tokenModifiers":["readonly","constant","documentation"],"tokenTypes":["operator","comment","type","function","string","namespace","variable","keyword"]},"signatureHelp":{"contextSupport":false,"dynamicRegistration":false,"signatureInformation":{"documentationFormat":["plaintext"],"parameterInformation":{"labelOffsetSupport":false}}},"synchronization":{"didSave":true,"dynamicRegistration":false,"willSave":false,"willSaveWaitUntil":false},"typeDefinition":{"dynamicRegistration":false,"linkSupport":false}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":false}},"workDoneProgress":true},"workspace":{"applyEdit":true,"codeLens":{},"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":false},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"workspaceEdit":{"changeAnnotationSupport":{},"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","delete","rename"]},"workspaceFolders":true}},"clientInfo":{"name":"kak-lsp","version":"14.1.0-snapshot"},"processId":12641,"rootPath":"/home/dude/workspace/test","rootUri":"file:///home/jo/workspace/test","trace":"off","workspaceFolders":[{"name":"/home/jo/workspace/test","uri":"file:///home/jo/workspace/test"}]},"id":0}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.334 DEBG To editor `12571`: evaluate-commands -client client0 -verbatim -- lsp-show-error 'language server is not initialized, parking request', module: kak_lsp::editor_transport:78
Dec 29 14:48:32.506 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Initialized server v. 4.1.3 for file:///home/dude/workspace/test"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.507 DEBG To editor `12571`: lsp-show-message-log 'Initialized server v. 4.1.3 for file:///home/dude/workspace/test', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.572 DEBG From server: {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":1,"completionProvider":{"resolveProvider":true,"triggerCharacters":["$","{"]},"hoverProvider":true,"documentHighlightProvider":true,"definitionProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true,"referencesProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix"],"resolveProvider":false,"workDoneProgress":false}}}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.572 DEBG To server: {"jsonrpc":"2.0","method":"initialized","params":{}}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.572 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"bash","text":"\nokduckduckMOREduck() {\n\tif [ -n \"$z\" ] ; then\n    \t\techo \"z\"\n\tfi\n\techo \"stuff okduckduck MORE duckduckduckduck MORE duckduckduckduck MORE duck duckduckduck MORE duckduckduckduck n#tu##r#tle\n#  MORE ko ko k\"\n    echo \"4000,5000,6000,7000,1000,2000,3000\"\n    if [ -z \"$z\" ]\n    \t\techo \"null\"\n    fi\n#\n# okokok MORE okokokok MORE ok\n#\n#\n# e\n# w\n#\n# ew\n# ew\n\n## this is a sentence.\n\n#this is a paragraphe. With some sentences.\n# More sentences.\n# MORE.\n#\n# Another sentence.\n\n# \n# ewe\n# #w\n# eew\n#\n# more data\n\necho \"end of myfunc2\"\n}\n\ntstfun() {\n    if [ -n \"3\" ] ; then\n        echo \"always true\"\n    fi\n    \n}\n\n\n#this is part 2\n##\n\n\nherefunct() {\n    case $x in $array\n\ta) echo \"a\";; b) echo \"b\";; *) echo \"*\";; esac\n\n}\n\n\n## end of file. Don't write under this.\n# O\n# OOOO\n# ooo\n# oo\n# oo\n#j\n#j\n#j\n########################\n#\n#\n#\n","uri":"file:///home/dude/workspace/test/test.sh","version":1}}}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.572 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/hover","params":{"position":{"character":1,"line":1},"textDocument":{"uri":"file:///home/dude/workspace/test/test.sh"}},"id":1}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.573 DEBG From server: {"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"d380d491-26d7-441d-9eb6-726c40630799","method":"workspace/didChangeConfiguration","registerOptions":{"section":"bashIde"}}]}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.573 DEBG From server: {"jsonrpc":"2.0","id":1,"method":"workspace/configuration","params":{"items":[{"section":"bashIde"}]}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.573 WARN Unsupported registration: workspace/didChangeConfiguration, module: kak_lsp::controller:451
Dec 29 14:48:32.573 DEBG To server: {"jsonrpc":"2.0","result":null,"id":0}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.573 DEBG To server: {"jsonrpc":"2.0","result":[null],"id":1}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:32.574 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"onHover 1:1 word=null"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.574 DEBG From server: {"jsonrpc":"2.0","id":1,"result":null}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.575 DEBG To editor `12571`: lsp-show-message-log 'onHover 1:1 word=null', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.593 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":2,"message":"updateConfiguration: failed with [\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"object\",\n    \"received\": \"null\",\n    \"path\": [],\n    \"message\": \"Expected object, received null\"\n  }\n]"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.593 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"Configuration loaded from client"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.593 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"ShellCheck: running \"shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/dude/workspace/test --source-path=/home/jo/workspace/test\""}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.593 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"BackgroundAnalysis: resolving glob \"**/*@(.sh|.inc|.bash|.command)\" inside \"file:///home/dude/workspace/test\"..."}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.594 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":2,"message":"ShellCheck: disabling linting as no executable was found at path 'shellcheck'"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.594 DEBG From server: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/dude/workspace/test/test.sh","version":1,"diagnostics":[]}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.594 DEBG To editor `12571`: lsp-show-message-log 'updateConfiguration: failed with [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "null",
    "path": [],
    "message": "Expected object, received null"
  }
]', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.596 DEBG To editor `12571`: lsp-show-message-log 'Configuration loaded from client', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.599 DEBG To editor `12571`: lsp-show-message-log 'ShellCheck: running "shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/dude/workspace/test --source-path=/home/jo/workspace/test"', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.600 DEBG To editor `12571`: lsp-show-message-log 'BackgroundAnalysis: resolving glob "**/*@(.sh|.inc|.bash|.command)" inside "file:///home/dude/workspace/test"...', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.602 DEBG To editor `12571`: lsp-show-message-log 'ShellCheck: disabling linting as no executable was found at path ''shellcheck''', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.604 DEBG To editor `12571`: evaluate-commands -buffer '/home/dude/workspace/test/test.sh' %§set-option buffer lsp_diagnostic_error_count 0; set-option buffer lsp_diagnostic_hint_count 0; set-option buffer lsp_diagnostic_info_count 0; set-option buffer lsp_diagnostic_warning_count 0; set-option buffer lsp_inline_diagnostics 1 ; evaluate-commands "set-option buffer lsp_diagnostic_lines 1  '0|%opt[lsp_diagnostic_line_error_sign]'"; set-option buffer lsp_inlay_diagnostics 1 §, module: kak_lsp::editor_transport:82
Dec 29 14:48:32.606 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"BackgroundAnalysis: Glob resolved with 3 files after 0.02 seconds"}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.607 DEBG To editor `12571`: lsp-show-message-log 'BackgroundAnalysis: Glob resolved with 3 files after 0.02 seconds', module: kak_lsp::editor_transport:82
Dec 29 14:48:32.623 DEBG From server: {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":4,"message":"BackgroundAnalysis: Completed after 0.037 seconds."}}, module: kak_lsp::language_server_transport:156
Dec 29 14:48:32.624 DEBG To editor `12571`: lsp-show-message-log 'BackgroundAnalysis: Completed after 0.037 seconds.', module: kak_lsp::editor_transport:82
Dec 29 14:48:35.152 DEBG From editor: 
session  = "12571"
client   = ""
buffile  = ""
filetype = ""
version  = 0
method   = "stop"
hook = true
[params]
, module: kak_lsp::editor_transport:127
Dec 29 14:48:35.152 INFO Shutting down language servers and exiting, module: kak_lsp::session:238
Dec 29 14:48:35.152 INFO Exit bash in project /home/dude/workspace/test, module: kak_lsp::session:243
Dec 29 14:48:35.152 INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:19
Dec 29 14:48:35.152 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:19
Dec 29 14:48:35.152 DEBG To server: {"jsonrpc":"2.0","method":"exit","params":null}, module: kak_lsp::language_server_transport:182
Dec 29 14:48:35.152 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:193
Dec 29 14:48:35.152 DEBG Waiting for language server process end, module: kak_lsp::language_server_transport:92
Dec 29 14:48:35.159 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:134
Dec 29 14:48:36.152 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:21
Dec 29 14:48:36.153 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:19
Dec 29 14:48:36.153 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:21
Dec 29 14:48:36.153 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:19
Dec 29 14:48:36.153 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:21
Dec 29 14:48:36.153 INFO ... Controller terminated with ok, module: kak_lsp::thread_worker:21
Dec 29 14:48:36.153 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:19
Dec 29 14:48:36.153 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:21
`


Here is my kak config:

`
evaluate-commands %sh{
        plugins="$kak_config/plugins"
            mkdir -p "$plugins"
                [ ! -e "$plugins/plug.kak" ] && \
                        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
                            printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "kak-lsp/kak-lsp" do %{
        cargo install --locked --force --path .
            # optional: if you want to use specific language servers
     mkdir -p ~/.config/kak-lsp
         cp -n kak-lsp.toml ~/.config/kak-lsp/
         }
set global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"

# relative line numbers
 hook global BufCreate .* %[
     add-highlighter buffer/ number-lines -relative -hlcursor
         add-highlighter buffer/ wrap
]

#indentation
set-option global tabstop     4
set-option global indentwidth 4


#tabs to spaces
hook global InsertChar \t %{
   exec -draft h@
   }

# Overwrites colors defined in kak-lsp
colorscheme gruvbox
`

**Comment by krobelus** [comment]
you need to call [`lsp-enable`](https://github.com/kak-lsp/kak-lsp/#configure-kakoune-to-enable-kak-lsp) to start the language server, show diagnostics in the gutter etc.

Some background info:
if you merely load kak-lsp, it will not actually spin up a language server.
Now `lsp-hover` requires a language server, so it starts one lazily.
When it does so, it prints the "parking request" message to communicate that it might take a few while.
It should return the accurate result after a few seconds here.
However, you still need lsp-enable for a few other things to work.

**Comment by jogood** [comment]
I see, now it works. I think the issue was that I thought lsp was enabled when it is not by default. I've added lsp-enable in my kakrc file. I've tried using lsp-diagnostics and lsp-diagnostics and lsp-diagnostic-lines-enable buffer/window but nothing happen although I've made different kind of mistakes (still in bash file), but I get nothing. Is this related to the language server?

**Comment by krobelus** [comment]
you're missing `shellcheck` which is an optional dependency for `bash-language-server`
I can tell from these log lines:

```
kak-lsp: log: ShellCheck: running "shellcheck --shell=bash --format=json1 --external-sources --source-path=file:///home/dude/workspace/test --source-path=/home/dude/workspace/test"
[...]
kak-lsp: log: ShellCheck: disabling linting as no executable was found at path 'shellcheck'
```

**Comment by jogood** [comment]
Great, now it works! Thank you very much.

I've simply installed shellcheck from my package manager and it worked.

Here is  the link to install shellcheck from different package manager:

https://github.com/koalaman/shellcheck#user-content-installing
