### ISSUE TITLE
Push kak-lsp to crates.io

### ISSUE THREAD

**Issue by EleanorNB** [kak-lsp/kak-lsp#660]
This will make installing and updating it much less fiddly. For instance I have a few other binaries installed through Cargo and I have a single command set up to automatically fetch updates and recompile only changed projects, but it only works if the projects are installed through crates.io; I'd really rather not have to replicate all that logic manually in my update script.

**Comment by krobelus** [comment]
sounds reasonable, will do soon

> I have a single command set up to automatically fetch updates and recompile only changed projects

To be clear that command is just `cargo install foo bar` that gives you caching for free, right?

**Comment by EleanorNB** [comment]
@krobelus No, as far as I know that doesn't work. I use a tool called `cargo-update` (from crates.io); that allows to `cargo install-update -a`. Such functionality really should be included in base Cargo but it isn't. (And the tool really should allow installing from local repo but it doesn't.)

**Comment by krobelus** [comment]
done
