### ISSUE TITLE
Only track the latest textDocument/references request

### ISSUE THREAD

**Issue by sclu1034** [kak-lsp/kak-lsp#666]
When the language server stalls for some reason (e.g. calculating a large set of semantic tokens) and the user continues to work and move the cursor, the editor will continuously generate `textDocument/references` requests (when auto references is enabled). Once the stall is over, kak-lsp will patch through all of those requests, resulting in lots of different tokens blinking one after another.

We might want some cache (maybe limited to a small size via LRU) that tracks those requests by ID and buffer, and when responses arrive, kak-lsp discards old IDs when the cache has a newer one.

**Comment by krobelus** [comment]
good point, [LSP intends clients to cancel stale requests](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationConsiderations)

> if a client sends a request to the server and the client state changes in a way that it invalidates the response it should do the following:
> - cancel the server request and ignore the result if the result is not useful for the client anymore. If necessary the client should resend the request.

There's even a new cancel request to tell the server to stop computing a response.
Though we will still receive a response and need to ignore it explicitly I think.

I wonder if there's a simple way to detect staleness.
If two instances of `textDocument/documentHighlight` have the same client but different position parameters, then we always want to discard the older one immediately, right? Because we don't want to send stale highlighting.
If all request parameters are identical then we also probably don't want to keep more than a few, maybe even just one..

request tokens are kept in `response_waitlist`, we can add a bit to mark requests as canceled

**Comment by krobelus** [comment]
this should work but I haven't tested it yet.
We probably should only ever cancel things that were sent from hooks (`meta.hook == true`).

```diff
diff --git a/src/context.rs b/src/context.rs
index f23a00c4..a3eb18ae 100644
--- a/src/context.rs
+++ b/src/context.rs
@@ -48,3 +48,3 @@ pub struct Context {
     pub request_counter: u64,
-    pub response_waitlist: HashMap<Id, (EditorMeta, &'static str, BatchNumber)>,
+    pub response_waitlist: HashMap<Id, (EditorMeta, &'static str, BatchNumber, bool)>,
     pub root_path: String,
@@ -161,3 +161,3 @@ impl Context {
             self.response_waitlist
-                .insert(id.clone(), (meta.clone(), R::METHOD, batch_id));
+                .insert(id.clone(), (meta.clone(), R::METHOD, batch_id, false));
 
@@ -179,2 +179,11 @@ impl Context {
 
+    pub fn cancel(&mut self, method: &'static str) {
+        for (id, (_meta, m, _batch_id, canceled)) in self.response_waitlist.iter_mut() {
+            if *m == method {
+                debug!("Canceling request {id:?} ({method})");
+                *canceled = true;
+            }
+        }
+    }
+
     pub fn reply(&mut self, id: Id, result: Result<Value, Error>) {
diff --git a/src/controller.rs b/src/controller.rs
index 25a22fd4..a3273f6b 100644
--- a/src/controller.rs
+++ b/src/controller.rs
@@ -153,3 +153,3 @@ pub fn start(
                             Output::Success(success) => {
-                                if let Some((meta, _, batch_id)) = ctx.response_waitlist.remove(&success.id) {
+                                if let Some((meta, _, batch_id, canceled)) = ctx.response_waitlist.remove(&success.id) {
                                     if meta.write_response_to_fifo {
@@ -158,2 +158,5 @@ pub fn start(
                                     }
+                                    if canceled {
+                                        continue;
+                                    }
                                     if let Some((batch_amt, mut vals, callback)) = ctx.batches.remove(&batch_id) {
@@ -173,3 +176,3 @@ pub fn start(
                                 if let Some(request) = ctx.response_waitlist.remove(&failure.id) {
-                                    let (meta, method, _) = request;
+                                    let (meta, method, _, canceled) = request;
                                     if meta.write_response_to_fifo {
@@ -178,2 +181,5 @@ pub fn start(
                                     }
+                                    if canceled {
+                                        continue;
+                                    }
                                     match failure.error.code {
diff --git a/src/language_features/highlight.rs b/src/language_features/highlight.rs
index d2f8e12d..57cbde9c 100644
--- a/src/language_features/highlight.rs
+++ b/src/language_features/highlight.rs
@@ -6,2 +6,3 @@ use crate::util::editor_quote;
 use itertools::Itertools;
+use lsp_types::request::Request;
 use lsp_types::{
@@ -29,2 +30,3 @@ pub fn text_document_highlight(meta: EditorMeta, params: EditorParams, ctx: &mut
     };
+    ctx.cancel(DocumentHighlightRequest::METHOD);
     ctx.call::<DocumentHighlightRequest, _>(
```

**Comment by krobelus** [comment]
I think semantic tokens allows to target a part of the buffer. I wonder if it's as good as treesitter

**Comment by sclu1034** [comment]
> I think semantic tokens allows to target a part of the buffer. I wonder if it's as good as treesitter

I really do need to spend some time looking into treesitter-based highlighting. But even though semantic tokens are annoyingly slow, they do work already.

**Comment by krobelus** [comment]
I've implemented the cache key as tuple `(method, buffer, client)`.
Each cache bucket has two slots for requests. Whenever a third request comes in, we evict the younger of the cached requests.
The idea is that the older one is probably closer to completion.
I wonder if we can find a scenario where we need more than two slots.

This is all in the `wip` branch, along with some work on https://github.com/kak-lsp/kak-lsp/issues/667
Will test drive and commit soon, I don't expect breakage.

> Do we even need to keep them around? Maybe "cancellation" could just be "remove from the waitlist and discard any response we aren't waiting for".

Right we can do that, probably other clients do the same. Will do

**Comment by krobelus** [comment]
> We might want some cache (maybe limited to a small size via LRU) that tracks those requests by ID and buffer, and when responses arrive, kak-lsp discards old IDs when the cache has a newer one.

hmm I failed to implement that behavior - we still apply all successful responses (only skippping canceled ones)

I think you're suggesting that we discard all responses if a younger request is in-flight (or has already retunred).
This would be easy to implement; since we have the sequential ID from JSON-RPC, it's enough to remember the highest (= youngest) ID for each cache key.
Not sure if this behavior causes problems.

**Comment by krobelus** [comment]
I've committed the cancel support in 950d0380a54071aac5f64601adb0bdeed2d480d8
If the server supports cancellation, then we should apply far fewer responses maybe that's good enough
I didn't test if it actually works in a congestion scenario (not sure how to provoke it)
