### ISSUE TITLE
Initial textDocument/semanticTokens/full fails.

### ISSUE THREAD

**Issue by vbauerster** [kak-lsp/kak-lsp#668]
Semantic tokens are not set until I either do some change or go to different file with `gd`.

Related log:
```
Jan 27 10:59:26.592 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:58
Jan 27 10:59:26.592 INFO Found project root "/home/vbauer/go/src/github.com/vbauerster/kampliment" because it contains "Cargo.toml", module: kak_lsp::project_root:41
Jan 27 10:59:26.592 DEBG Routing editor request to Route { session: "695999", language: "rust", root: "/home/vbauer/go/src/github.com/vbauerster/kampliment" }, module: kak_lsp::session:112
Jan 27 10:59:26.592 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/vbauer/go/src/github.com/vbauerster/kampliment/src/main.rs"}},"id":3}, module: kak_lsp::language_server_transport:182
Jan 27 10:59:26.592 DEBG From server: {"jsonrpc":"2.0","id":3,"error":{"code":-32801,"message":"waiting for cargo metadata or cargo check"}}, module: kak_lsp::language_server_transport:156
Jan 27 10:59:26.592 ERRO Error response from server: Failure { jsonrpc: Some(V2), error: Error { code: ServerError(-32801), message: "waiting for cargo metadata or cargo check", data: None }, id: Num(3) }, module: kak_lsp::controller:171
```

This happens with master version only. Switching to `kak-lsp 14.1.0` (both binary and rc/lsp.kak) fixes the problem.

**Comment by vbauerster** [comment]
Just tested with `c5645e7` patch, issue is still there. It's apparent if disabling builtin highlighter.

```kak
hook global WinSetOption filetype=rust %{
    remove-highlighter window/rust
}
```

**Comment by krobelus** [comment]
I think it now behaves the same as `v14.1.0`.
Highlighting works for me if I move the cursor once rust-analyzer is ready.
We could improve the behavior by periodically retrying `textDocument/semanticTokens/full` until we get a non-error response. I think this could be added to the controller logic.

Then we can also get rid of the redundant semantic tokens requests sent by c5645e7c8bc7c3508cf04939af3e365e248de8b0. That would probably be the more elegant solution. I wonder if other LSP clients do the same

**Comment by vbauerster** [comment]
Strange if I move cursor, there is still no any highlighting. Log shows empty response from the server:
```
Jan 28 09:45:20.971 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/vbauer/go/src/github.com/vbauerster/kampliment/src/main.rs"}},"id":3}, module: kak_lsp::language_server_transport:182
Jan 28 09:45:20.971 DEBG From server: {"jsonrpc":"2.0","id":3,"result":{"resultId":"1","data":[]}}, module: kak_lsp::language_server_transport:156
```

**Comment by vbauerster** [comment]
Strange if I move cursor, there is still no any highlighting. Log shows empty response from the server:
```
Jan 28 09:45:20.971 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/vbauer/go/src/github.com/vbauerster/kampliment/src/main.rs"}},"id":3}, module: kak_lsp::language_server_transport:182
Jan 28 09:45:20.971 DEBG From server: {"jsonrpc":"2.0","id":3,"result":{"resultId":"1","data":[]}}, module: kak_lsp::language_server_transport:156
```

**Comment by vbauerster** [comment]
Strange if I move cursor, there is still no any highlighting. Log shows empty response from the server:
```
Jan 28 09:45:20.971 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/vbauer/go/src/github.com/vbauerster/kampliment/src/main.rs"}},"id":3}, module: kak_lsp::language_server_transport:182
Jan 28 09:45:20.971 DEBG From server: {"jsonrpc":"2.0","id":3,"result":{"resultId":"1","data":[]}}, module: kak_lsp::language_server_transport:156
```

**Comment by krobelus** [comment]
Interesting. I never got the empty response with rust-analyzer 1 (ff4d55e48 2023-01-15) but of course this could depend on the project.
It'd be easy to treat the empty response like an error response.
Whether that's good enough I don't know. Do servers send partial results?

**Comment by krobelus** [comment]
Maybe we should switch to `semanticTokens/refresh`.

**Comment by vbauerster** [comment]
Here is full log:
[kak-lsp.log.gz](https://github.com/kak-lsp/kak-lsp/files/10526959/kak-lsp.log.gz)

**Comment by vbauerster** [comment]
> Interesting. I never got the empty response with rust-analyzer 1 (ff4d55e48 2023-01-15) but of course this could depend on the project.

version I use: rust-analyzer 1 (daa0138e4 2023-01-21)

**Comment by krobelus** [comment]
Nice, I can reproduce on your `src/main.rs`.
Feels like a bug in rust-analyzer but I don't know much about semantic tokens.
I don't think it makes sense to re-request semantic tokens on every cursor move (hence 9621c99d)

**Comment by vbauerster** [comment]
It is not specific to [kamp](https://github.com/vbauerster/kampliment) in my case, happens in any rust based project.

**Comment by vbauerster** [comment]
> I don't think it makes sense to re-request semantic tokens on every cursor move (hence https://github.com/kak-lsp/kak-lsp/commit/9621c99d8ad358af806d4d88f43cd1e50bec87c7)

Agree.

**Comment by krobelus** [comment]
I think this  is a race condition in rust-analyzer, reported as https://github.com/rust-lang/rust-analyzer/issues/14048
Presumably, LSP doesn't specific how to deal with this issue :(
