### ISSUE TITLE
Can't select code actions

### ISSUE THREAD

**Issue by dutrieuc** [kak-lsp/kak-lsp#669]
I'm using the LSP included in https://github.com/mickael-menu/zk

This LSP generates these code actions that can't be selected in kakoune.  
I can see the 💡 and the code actions show up in the kak-lsp logs.

Since there is no command.title kak-lsp won't list them above kakoune prompt (or it will list them as empty strings I guess).
To test this idea, I edited [this line](https://github.com/kak-lsp/kak-lsp/blob/c5645e7c8bc7c3508cf04939af3e365e248de8b0/src/language_features/code_action.rs#L152) to:
```
CodeActionOrCommand::Command(command) => "command_title",
```
And then I was able to select the code action.

This looks like an issue with the zk lsp as well but I think since this might silently hide available code actions it could be worth fixing here as well.

----

Code action example 
```
Action: CodeAction
{ title: "New note in current directory",
kind: Some(CodeActionKind("refactor")),
diagnostics: None,
edit: None,
command: Some(Command
	{ title: "",
	command: "zk.new",
	arguments: Some([String("/home/cydu/zk/personal/journals"),
	Object {"content": String(""),
	"date": String(""),
	"dir": String("/home/cydu/zk/personal/journals"),
	"edit": Bool(false),
	"extra": Null,
	"group": String(""),
	"insertLinkAtLocation": Object {"range": Object {"end": Object {"character": Number(138),
	"line": Number(13)},
	"start": Object {"character": Number(0),
	"line": Number(13)}},
	"uri": String("file:///home/cydu/zk/personal/journals/2023-02-03.md")},
	"template": String(""),
	"title": String("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")}]) }
),
is_preferred: None,
disabled: None,
data: None }
```

**Comment by sclu1034** [comment]
This is definitely an upstream issue. kak-lsp has no way to generate a fitting title, it must come from the LSP server.
Which is also why kak-lsp can't really do all that much better than it already does. The only other field (`command`) is not meant for the UI, so it could be arbitrarily long and unreadable.

I guess the most sensible fallback for kak-lsp, if anything, would be something like `"Error: The `title` field is empty"`, so that at least the inevitable issue reports are less dubious than "nothing shows up".

**Comment by dutrieuc** [comment]
I think other LSP clients may use the CodeAction title as a fallback.

**Comment by mickael-menu** [comment]
I merged in the fix from @dutrieuc for `zk`. But IMHO `kak-lsp` should display the Code action title instead of the Command title, in this particular case.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction

**Comment by krobelus** [comment]
Due to an oversight kak-lsp always used the command title if there was a command.
I changed it to always using the code action's title, I think that's correct. Thanks
