### ISSUE TITLE
Is there a way to change configuration at runtime?

### ISSUE THREAD

**Issue by Roger** [kak-lsp/kak-lsp#670]
I would like to change rust-analyzer config at runtime so I can set `cargo.target` to `wasm32-unknown-unknown`.

The use case is that, sometimes in a project that supports both native and wasm, I can't run `cargo check` or go to definitions because `code is inactive due to #[cfg] directives: target_arch = "wasm32" is disabled`, so it would be nice to be able to change the target, even if that means restarting rust-analyzer.

**Comment by krobelus** [comment]
this should work (I didn't test it). 

```kak
set-option global lsp_config %{
	[language.rust.settings.rust-analyzer]
	cargo.target = "wasm32-unknown-unknown"
}
```

it will override whatever `[language.rust.settings.rust-analyzer]` is in your kak-lsp.toml, so you might need to copy that over.

If that doesn't work for some reason, you could change lsp_cmd dynamically to set a different kak-lsp.toml (and restart)

**Comment by Roger** [comment]
That did the trick! next to those lines I've added:

```
lsp-stop
lsp-start
```

Thanks!

**Comment by krobelus** [comment]
it should not be necessary to restart the language server, rust-analyzer is sent a notification whenever you change the `lsp_config` option

**Comment by Roger** [comment]
hmm, seems to be ignoring the change of configuration somehow, I tried again without the restart and doesn't work. I can see `kak-lsp: config-change detected` in debug buffer including `cargo.target`
