### ISSUE TITLE
Completion for TypeScript is acting weird

### ISSUE THREAD

**Issue by gbrlsnchs** [kak-lsp/kak-lsp#674]
This is the first time I see something like this happening, and it only happens for TypeScript files (so not for JavaScript ones). Also, it's not happening for any other LSP server I use (Go, Rust, Zig...), only for TypeScript.

Interestingly, for comparison purposes, the same LSP setup works for Helix, so it seems to be some issue between kak-lsp and typescript-language-server.

Now, to reproduce this, it is as simple as creating a TypeScript file (say, `main.ts`) and then typing:

```typescript
const now = new Date();
```

Then, when trying to access `now` methods, they only show up after inserting the dot:

![1677264045](https://user-images.githubusercontent.com/7577128/221263856-23b1ccaa-48e1-454c-b795-455ac1f0e2d5.png)

However, no documentation popup show up for those methods. But if you press <kbd>Esc</kbd>, the documentation popup will show up at the top of the window:

![1677264080](https://user-images.githubusercontent.com/7577128/221263976-72866932-bc28-4c84-b52f-2ebef07e8d05.png)

![1677263855](https://user-images.githubusercontent.com/7577128/221263335-740d03e4-5b63-4afd-ad45-88dda675498a.png)

And finally, typing anything after the dot renders no LSP suggestions.

All other functionality is working properly: diagnostics, code actions, renaming, goto-definition, etc, but completion.

**Comment by krobelus** [comment]
thanks, should be fixed.
there is some work left to show all completions independent of how the language server sends them

**Comment by gbrlsnchs** [comment]
As always, thanks for your dedication. It's working now! :grin:
