### ISSUE TITLE
`lsp-show-message-request-next` has extraneous quotes and doesn't display message from Lua language server

### ISSUE THREAD

**Issue by raiguard** [kak-lsp/kak-lsp#683]
![image](https://user-images.githubusercontent.com/3515394/233730856-0f796b1b-5ab5-4432-a231-c2235bec804f.png)

![image](https://user-images.githubusercontent.com/3515394/233730964-01c0bb9b-225b-4958-b6cd-b9b1353f7897.png)

Unfortunately, reproduction is a bit tricky:

- Install [Factorio](https://factorio.com) (I think it will work fine with the free demo)
- Install [factoriomod-debug](https://www.npmjs.com/package/factoriomod-debug) and the [LuaLS language server](https://github.com/LuaLS/lua-language-server)
- Run `fmtk sumneko-3rd -d /path/to/runtime-api.json /some/other/path`
- Add `workspace.userThirdParty = ["/some/other/path"]` to kak-lsp.toml
- Open any Lua file in kak
- See message request

Because of the very involved reproduction, I'll see if I can submit a fix myself. Thanks for your hard work!

**Comment by krobelus** [comment]
The quotes look fine, the problem is that `-on-abort` is suggested as well.
This is a recent regression, will fix.
It should only apply to Kakoune versions before 2022.10.31 so I'm surprised to hear this.

**Comment by krobelus** [comment]
ok assuming you are using a recent Kakoune I don't think I actually fixed it.
Try to get a log, it should be doable to find where the quotes are missing.

**Comment by raiguard** [comment]
I'm on a custom branch with various patches, but it tracks latest kakoune master. I pulled your changes and it has fixed both issues. Thanks!

![image](https://user-images.githubusercontent.com/3515394/233742220-609e2b3c-8321-419e-b9d1-e4f279308034.png)
