### ISSUE TITLE
Suggested latex reverse search command is not working

### ISSUE THREAD

**Issue by gnull** [kak-lsp/kak-lsp#688]
https://github.com/kak-lsp/kak-lsp/blob/7c8c71a90f524a473dceaf08e499b531a7bec4cb/kak-lsp.toml#L233

The command for reverse search (i.e. clicking on your document in pdf viewer to make editor jump to the corresponding source location) that's suggested in the config file now is not working. It gives me this error:

```
': 2:17: 'evaluate-commands': no such client: 'opt{texlab_client}'
error running command '
                evaluate-commands -client opt{texlab_client} {
                    evaluate-commands -try-client opt{jumpclient} {
                        edit -- {input} {line}
                    }
                }
```

It seems that something has changed on Kakoune side and we need to update kak-lsp config accordingly. Does anyone know how to modify that command to make reverse search work correctly?

Ivan

**Comment by krobelus** [comment]
works for me with latest master of Kakoune and kak-lsp.
Looks like something is stripping the %, for example it should be `%opt{texlab_client}`. Maybe your shell does that? What's your kak-lsp.toml? The default one uses `sh -c '...'`

**Comment by krobelus** [comment]
with the default kak-lsp.toml, `ps aux | grep zathura | grep [%]opt` should show the running pdf viewer

**Comment by krobelus** [comment]
I'm looking for a way to reproduce.
What's the output of

	ps aux | grep -o 'zathura .*' | sed 's/ \+/ /g'

It should be something like

	zathura /tmp/test.pdf --synctex-forward 1:1:/tmp/test.tex --synctex-editor-command sh -c ' echo " evaluate-commands -client %opt{texlab_client} %{ evaluate-commands -try-client %opt{jumpclient} %{ edit -- %{input} %{line} } } " | kak -p $kak_session ' 

if that has % (in %opt{texlab_client}, then the problem could be in $(which sh)
if it doesn't have %, then maybe zathura is at fault

What are your versions of sh, zathura, Kakoune, kak-lsp?
Does it reproduce with the [default configuration](https://github.com/kak-lsp/kak-lsp/#default-configuration)? (that one will rule out any customization from your $HOME)

**Comment by krobelus** [comment]
> Do you have an idea of who could be doing the expansion of %?

Maybe zsh? what's `file $(which sh)`
Will give more info later.

> $ mv .config/kak-lsp/kak-lsp.toml .config/kak-lsp/backup
> $ HOME=$(mktemp -d) kak -e '

no need to move the config if you override HOME

**Comment by krobelus** [comment]
```
$ zathura --version
zathura 0.5.2
girara 0.3.9 (runtime: 0.4.0)
(plugin) pdf-mupdf (0.4.1) (/usr/lib/zathura/libpdf-mupdf.so)
```
