### ISSUE TITLE
 'unmap': cannot unmap key that is currently executing 

### ISSUE THREAD

**Issue by altunyurt** [kak-lsp/kak-lsp#689]
I'm not really sure if it's directly related to kak-lsp but sometimes completion fails and leaves kakoune unresponsive for mode switch, esc key does not work. 

I see the following logs in the debug buffer. 

```log
error running hook InsertCompletionHide(3.39,3.58)/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
error running hook InsertCompletionHide()/: 4:5: 'unmap': cannot unmap key that is currently executing
```

There's another similar issue on autopairs repo https://github.com/alexherbo2/auto-pairs.kak/issues/60 referring to this commit in kakoune tree https://github.com/mawww/kakoune/commit/e49c0fb04095a2a1c546fd033ce2a1a6df3eb8d0

Parent commit of the one above, seems not to have this issue and works fine.

**Comment by krobelus** [comment]
wow how has that bug report not reached me for one month; thanks for reporting this
can you post your `InsertCompletionHide` hook? Maybe there is a workaround. Else we could allow map/unmap during mapping execution

**Comment by altunyurt** [comment]
Here're the hooks for show and hide 

```
set -remove global autocomplete insert 
hook global InsertCompletionShow .* %{
    map window insert <esc>   '<c-o>'
    map window insert <c-q>   '<c-o>'
}
hook global InsertCompletionHide .* %{
    unmap window insert <esc>   '<c-o>'
    unmap window insert <c-q>   '<c-o>'
}

```

**Comment by krobelus** [comment]
seems legit, https://github.com/mawww/kakoune/pull/4945 proposes a fix
