### ISSUE TITLE
Only first command with `window` scope is setting correct hooks when using `filetype` hook

### ISSUE THREAD

**Issue by rosingrind** [kak-lsp/kak-lsp#692]
## Summary

At first, I've thought that this is a #581 issue: no inlay hints were present, only changing the buffer sometimes made them to appear (after config tweaking).

Trying to set up `kak-lsp` per window as stated in [readme](https://github.com/kak-lsp/kak-lsp/blob/v14.2.0/README.asciidoc#configure-kakoune-to-enable-kak-lsp), I have discovered that only first command in a sequence will set up hooks:

- using the sample config, open a rust file
- `:lsp-inline-diagnostics-enable window` throws an error
- `:lsp-inlay-hints-enable window` actually enables inlay hints (no error)
- same with code lenses, etc.

Using these commands as `global` appears to set required hooks, but inlay hints are still shown after the buffer change. This issue is about `global`/`window` hooks problem, but my guess is that #581 may be related.

## Config

```kakounescript
hook global WinSetOption filetype=(rust) %{
    lsp-enable-window
    lsp-inline-diagnostics-enable window # set for window
    lsp-inlay-hints-enable window # not set
    lsp-inlay-code-lenses-enable window # not set
    # ...
}
```

## Info

- `kak-lsp` v14.2.0 installed with `cargo`
- `kakoune` v2023.08.05 from `brew`

**Comment by rosingrind** [comment]
I assume that this may not be a `kak-lsp` issue and it should be upstreamed to `kakoune`. I've checked https://github.com/kak-lsp/kak-lsp/blob/12bad0b5e4e6eb0dd567701fcd02a7247f6f3ef7/rc/lsp.kak#L2006-L2011 and it seems that there's no way it may break like that, but I'd like to ensure this assumption - maybe I do miss something there

**Comment by krobelus** [comment]
> ```kakounescript
> hook global WinSetOption filetype=(rust) %{
>     lsp-enable-window
>     lsp-inline-diagnostics-enable window # set for window
>     lsp-inlay-hints-enable window # not set
>     lsp-inlay-code-lenses-enable window # not set
>     # ...
> }
> ```

>- `:lsp-inline-diagnostics-enable window` throws an error

Errors in Kakoune work like exceptions so they stop execution of the current command (in this case hook).
That's why the other commands are not executed. To continue executing use `try { ... }; ...`.

Now the reason why the `lsp-inline-diagnostics-enable window` fails is because it is already enabled by default (it is run as part of `lsp-enable-window`).
The error you got is

	Error: 1:1: 'lsp-inline-diagnostics-enable': 2:5: 'add-highlighter': duplicate id: 'lsp_inline_diagnostics'

Knowing some internals, this error message makes a ton of sense. But we should probably rephrase it as "lsp-inline-diagnostics-enable: already enabled".

**Comment by rosingrind** [comment]
I've used `try` and the problem is gone, thank you! I'm pretty new to kakoune, so haven't thought about where to search for `kak-lsp` defaults (`/rc/lsp.kak: ### Default integration ###` obv for anyone like me) and how to handle them properly, so thank you for such a quick and detailed explanation, and for this awesome tool!
