### ISSUE TITLE
Wrong ropey version in Cargo.toml

### ISSUE THREAD

**Issue by Franciman** [kak-lsp/kak-lsp#705]
In the Cargo.toml of kak-lsp it's written that ropey can be version 1.2.0,
but it does not seem to compile with this version, while with version 1.6.0 everything works fine.
https://github.com/kak-lsp/kak-lsp/blob/e97be1592a28f75a53a7a57e23df117fa6a8e66b/Cargo.toml#L29

Furthermore in the Cargo.lock it's written that ropey is version 1.6.0, why is this?

**Comment by krobelus** [comment]
how to reproduce the failure?

**Comment by krobelus** [comment]
I opened https://github.com/kbknapp/cargo-outdated/issues/378
