### ISSUE TITLE
Support for basic Markdown parsing

### ISSUE THREAD

**Issue by maximbaz** [kak-lsp/kak-lsp#73]
Contrary to declaring kak-lsp as the one which can only understand plaintext format, it would be cool if kak-lsp could actually parse markdown and show me some bold and italic text in the info box. I think even a basic support for `**bold** __bold__ *italic* _italic_` would be enough for most documentation.

**Comment by Delapouite** [comment]
> Edit: It actually does have markup, so it could be possible

@JJK96 How do you use markup with the `:info` command?

The `:echo` command has it:
```
:echo -markup {red+b}foo
```

But I can't find the equivalent for `:info`. I thinks it's currently impossible.

**Comment by JJK96** [comment]
I found that it was possible for echo, I assumed that it would work the same way for info boxes. 

Apparently, there is indeed no markup for info boxes atm.

**Comment by ul** [comment]
Apparently there was not, created one.

**Comment by maximbaz** [comment]
Feel free to keep this ticket closed since it's not actionable at the moment, I'll remind you when upstream issue gets solved 😉

**Comment by Delapouite** [comment]
Upstream got fixed: https://github.com/mawww/kakoune/commit/cb1b03c0db91d85db3545a49f68d63fad0fe137c

**Comment by aecepoglu** [comment]
A subset of markdown would be OK to start with:

```
code
  blocks
```
`inline codes`, _italic_ and *bold* would suffice.

**Comment by eikenb** [comment]
Is there a workaround for this until the draft fix is finished and merged?

**Comment by clad26** [comment]
Any update to this? Was someone able to achieve this?
